force-app/main/default/objects/App_Data__c/App_Data__c.object-meta.xml
<CustomObject>
    <label>App Data</label>
    <nameField>
        <displayFormat>ADN-{00}</displayFormat>
        <label>App Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>App Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/App_Data__c/fields/Privacy_Policy__c.field-meta.xml
<CustomField>
    <fullName>Privacy_Policy__c</fullName>
    <label>Privacy Policy</label>
    <length>50000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/App_Data__c/fields/Terms_and_Conditions__c.field-meta.xml
<CustomField>
    <fullName>Terms_and_Conditions__c</fullName>
    <label>Terms and Conditions</label>
    <length>80000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/classes/WS_SendPolicyAndTnC.cls
@RestResource(urlMapping='/PoilcyAndTnCFetch')
global class WS_SendPolicyAndTnC {

    global class SFDCtoMobileApp {
        public String tnc;
        public String privacy_policy;	
        public String status;
        public String message;
    }

    @HttpGet
    global static SFDCtoMobileApp sendData(){
        SFDCtoMobileApp data = new SFDCtoMobileApp();
        data.tnc = '';
        data.privacy_policy = '';

        try{
            List<App_Data__c> appDataList = [SELECT Id, Name, Privacy_Policy__c, Terms_and_Conditions__c FROM App_Data__c ORDER BY LastModifiedDate DESC LIMIT 1];
            if(!appDataList.isEmpty()){
                data.tnc = appDataList[0].Terms_and_Conditions__c;
                data.privacy_policy = appDataList[0].Privacy_Policy__c;
            }
        }catch(exception e){
            data.status = 'Error';
            data.message = e.getMessage();
        }
        return data;
    }

}