force-app/main/default/objects/Case_Progress_Detail__c/Case_Progress_Detail__c.object-meta.xml
<CustomObject>
    <label>Case Progress Detail</label>
    <nameField>
        <displayFormat>CPD-{0000}</displayFormat>
        <label>Case Progress Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Progress Details</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Progress_Detail__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case Progress Details</relationshipLabel>
    <relationshipName>Case_Progress_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case_Progress_Detail__c/fields/CS_Remarks__c.field-meta.xml
<CustomField>
    <fullName>CS_Remarks__c</fullName>
    <label>CS Remarks</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case_Progress_Detail__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Responded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case_Progress_Detail__c/fields/WH_Team_Remarks__c.field-meta.xml
<CustomField>
    <fullName>WH_Team_Remarks__c</fullName>
    <label>Refund/WH Team Remarks</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/followUpControllerTest.cls
@isTest
public class followUpControllerTest {
    @isTest
    static void testClass(){
        //followUpController.dumMethod();
        Profile p = [SELECT Id FROM Profile WHERE Name='WareHouse Team' LIMIT 1];
        
        User testUser = new User(Alias = 'standt', Email='dipesh@test.com',
                                 EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
                                 LocaleSidKey='en_US', ProfileId = p.Id, TimeZoneSidKey='America/Los_Angeles',
                                 UserName='dipe12345678sh.m@kult.app');
        insert testUser;
        
        set<Id> cseId = new set<Id>();
        Case testCase = new Case(Status= 'New', Subject = 'Test Case');
        insert testCase;
        cseId.add(testCase.Id);
        system.debug('testCase.Id=============>'+testCase.Id);


		Case testCase1 = new Case(Status= 'New', Subject = 'Test Case');
        insert testCase1;		
        
        Case_Progress_Detail__c cpd = new Case_Progress_Detail__c();
        cpd.WH_Team_Remarks__c = 'Test1';
        cpd.CS_Remarks__c = 'refundReason';
        cpd.Status__c = 'In Progress'; 
        cpd.Case__c = testCase.Id;
        insert cpd;
        
        Case_Progress_Detail__c cpd1 = new Case_Progress_Detail__c();
        cpd1.WH_Team_Remarks__c = 'Test1';
        cpd1.CS_Remarks__c = 'refundReason';
        cpd1.Status__c = 'Open'; 
        cpd1.Case__c = testCase1.Id;
        insert cpd1;

        system.runAs(testUser){            
            System.debug('Current User============> ' + UserInfo.getUserName());
            System.debug('Current Profile=============>' + UserInfo.getProfileId());
        }
        followUpController.sendFollowUp(testCase.Id,'remarks');
        followUpController.sendFollowUpWithAttachment(testCase.Id,'remarks','Banoj file','hi','Debug Logs Content Type');
        followUpController.sendFollowUpResponse(testCase.Id,'remarks');
        followUpController.checkFollowUpStatu(testCase1.Id);
        followUpController.checkFollowUpStatu(testCase.Id);
        
    }
}