force-app/main/default/objects/Case_Progress_Detail__c/Case_Progress_Detail__c.object-meta.xml
<CustomObject>
    <label>Case Progress Detail</label>
    <nameField>
        <displayFormat>CPD-{0000}</displayFormat>
        <label>Case Progress Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Progress Details</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Progress_Detail__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case Progress Details</relationshipLabel>
    <relationshipName>Case_Progress_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case_Progress_Detail__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Responded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case_Progress_Detail__c/fields/WH_Team_Remarks__c.field-meta.xml
<CustomField>
    <fullName>WH_Team_Remarks__c</fullName>
    <label>Refund/WH Team Remarks</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/caseProgressDetailTriggerHelperTest.cls
@IsTest(SeeAllData=true)

public class caseProgressDetailTriggerHelperTest {
    @isTest
    static void testClass(){
        //caseProgressDetailTriggerHelper.dumMethod();
        Profile prorec = [SELECT Id, Name FROM Profile WHERE Name ='WareHouse Team' LIMIT 1]; 
        User salesALsUser = new User(
            Username = 'testuser@salesals.com', 
            FirstName = 'Test', 
            LastName = 'User', 
            Email = 'testuser@salesals.com', 
            Alias = 'testuser', 
            TimeZoneSidKey = 'America/Los_Angeles', 
            LocaleSidKey = 'en_US', 
            EmailEncodingKey = 'UTF-8', 
            LanguageLocaleKey = 'en_US', 
            ProfileId = prorec.Id
        );
        // User use = [sELECT Id,Name,ProfileId FROM User where ProfileId =:prorec.Id LIMIT 1];
        Case cs = new Case();
        cs.Status = 'New';
        insert cs;
        List<Case_Progress_Detail__c> caseObjList = new List<Case_Progress_Detail__c>();
        Case_Progress_Detail__c caseObj = new Case_Progress_Detail__c();
        caseObj.WH_Team_Remarks__c = 'Test';
        caseObj.Status__c = 'Responded'; 
        caseObj.Case__c = cs.Id;
        insert caseObj;
        caseObjList.add(caseObj);
        
        caseObj.WH_Team_Remarks__c = 'eeee';
        update caseObj;
        
        caseProgressDetailTriggerHelper.sendNotificationToCSTeam(caseObjList);
    }
    
    
}