force-app/main/default/objects/Case/fields/Caption__c.field-meta.xml
<CustomField>
    <fullName>Caption__c</fullName>
    <label>Caption</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Case/fields/Case_Communication__c.field-meta.xml
<CustomField>
    <fullName>Case_Communication__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case Communication</label>
    <referenceTo>Case_Communication__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Post_Comments__c.field-meta.xml
<CustomField>
    <fullName>Post_Comments__c</fullName>
    <label>Post Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/Post_Id__c.field-meta.xml
<CustomField>
    <fullName>Post_Id__c</fullName>
    <externalId>true</externalId>
    <label>Post Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case/fields/POST_URL__c.field-meta.xml
<CustomField>
    <fullName>POST_URL__c</fullName>
    <label>POST URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Case/fields/Type_of_Post__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Post__c</fullName>
    <label>Type of Post</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tags</fullName>
            </value>
            <value>
                <fullName>Mentions</fullName>
            </value>
            <value>
                <fullName>Hashtags</fullName>
            </value>
            <value>
                <fullName>Post</fullName>
            </value>
            <value>
                <fullName>DM</fullName>
            </value>
            <value>
                <fullName>Reel</fullName>
            </value>
            <value>
                <fullName>Comment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case_Communication__c/Case_Communication__c.object-meta.xml
<CustomObject>
    <label>Case Communication</label>
    <nameField>
        <displayFormat>CaseComm-{0000}</displayFormat>
        <label>Case Communication Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Communications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Communication__c/fields/Activity_Author__c.field-meta.xml
<CustomField>
    <fullName>Activity_Author__c</fullName>
    <label>Activity Author</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Communication__c/fields/Activity_Content__c.field-meta.xml
<CustomField>
    <fullName>Activity_Content__c</fullName>
    <label>Activity Content</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Case_Communication__c/fields/Activity_Created_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Activity_Created_DateTime__c</fullName>
    <label>Activity Created DateTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case_Communication__c/fields/Activity_ID__c.field-meta.xml
<CustomField>
    <fullName>Activity_ID__c</fullName>
    <externalId>true</externalId>
    <label>Activity ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case_Communication__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case Communications</relationshipLabel>
    <relationshipName>Case_Communications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Case_Communication__c/fields/Case_Communication__c.field-meta.xml
<CustomField>
    <fullName>Case_Communication__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case Communication</label>
    <referenceTo>Case_Communication__c</referenceTo>
    <relationshipLabel>Case Communications</relationshipLabel>
    <relationshipName>Case_Communications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case_Communication__c/fields/Platform_URL__c.field-meta.xml
<CustomField>
    <fullName>Platform_URL__c</fullName>
    <label>Activity Source URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/instaComponentControllerTest.cls
@isTest(seeAllData=true)
public class instaComponentControllerTest { 
    
    @isTest
    static void testGetRepliesDetails() {
        
        // Create a test Case record
        Case testCase = new Case();
        testCase.Subject = 'Test Case';
        testCase.Description = 'Test Case Description';
        insert testCase;
        string caseId = testCase.id;

        // Create test data for the Post_Comments__c object
        Case_Communication__c commentRecord = new Case_Communication__c();
        commentRecord.Activity_ID__c = 'TestCommentId';
        commentRecord.Activity_Content__c = 'RepliesWrapper:[data=(ReplyData:[id=18229403821211947, text=@sagarikaranaa its AMAZING, timestamp=2023-07-30T19:15:50+0000, username=kavyajhunjhunwala])]';
        commentRecord.Case__c = caseId;
        insert commentRecord;
        
        // Set the mock for the HTTP callout
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());

        // Call the getRepliesDetails method with the test data
        Test.startTest();
        List<instaComponentController.ReplyWrapperRecords> replyList = instaComponentController.getRepliesDetails(commentRecord.Activity_ID__c);
        Test.stopTest();
    }
    
    @isTest
    static void testGetCaseDetails() {
        // Create a test Case record
        Case testCase = new Case();
        testCase.Subject = 'Test Case';
        testCase.Description = 'Test Case Description';
        insert testCase;

        // Create a test Case_Communication__c record associated with the Case
        Case_Communication__c commentRecord = new Case_Communication__c();
        commentRecord.Activity_ID__c = 'TestCommentId';
        commentRecord.Activity_Author__c = 'Test Comment';
        commentRecord.Platform_URL__c = 'https://www.example.com/test-post-url';
        commentRecord.Activity_Created_DateTime__c = Datetime.now();
        commentRecord.Activity_Content__c = 'RepliesWrapper:[data=(ReplyData:[id=18229403821211947, text=@sagarikaranaa its AMAZING, timestamp=2023-07-30T19:15:50+0000, username=kavyajhunjhunwala])]';
        commentRecord.Case__c = testCase.Id;
        insert commentRecord;

        // Set the mock for the HTTP callout
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());

        // Call the getCaseDetails method with the test data
        Test.startTest();
        List<instaComponentController.instaWrapper> instaWrapperList = instaComponentController.getCaseDetails(testCase.Id);
        Test.stopTest();
    }
    
    @isTest
    static void testReplyToComment() {
        // Create a test Case record
        Case testCase = new Case();
        testCase.Subject = 'Test Case';
        testCase.Description = 'Test Case Description';
        insert testCase;

        // Create a test Case_Communication__c record
        Case_Communication__c commentRecord = new Case_Communication__c();
        commentRecord.Activity_ID__c = 'TestCommentId';
        commentRecord.Activity_Content__c = null; // Simulating no replies
        commentRecord.Case__c = testCase.Id;
        commentRecord.Activity_Content__c = 'RepliesWrapper:[data=(ReplyData:[id=18229403821211947, text=@sagarikaranaa its AMAZING, timestamp=2023-07-30T19:15:50+0000, username=kavyajhunjhunwala])]';
        insert commentRecord;

        // Set the mock for the HTTP callout
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());

        // Call the replyToComment method with the test data
        Test.startTest();
        instaComponentController.replyToComment('TestCommentId', 'Test reply message');
        Test.stopTest();
    }
    
    @isTest
    static void testGetUpdateComments() {
        // Create a test Case record
        Case testCase = new Case();
        testCase.Subject = 'Test Case';
        testCase.Description = 'Test Case Description';
        insert testCase;

        // Create a test Case_Communication__c record
        Case_Communication__c commentRecord = new Case_Communication__c();
        commentRecord.Activity_ID__c = '18229403821211947';
        commentRecord.Activity_Content__c = null; // Simulating no replies
        commentRecord.Case__c = testCase.Id;
        insert commentRecord;

        Case CaseDetails = [SELECT Id, Subject, Post_Id__c, Description, Type_of_Post__c, Caption__c, POST_URL__c,
            (SELECT Activity_ID__c, Activity_Created_DateTime__c, Activity_Content__c, Activity_Author__c, Platform_URL__c
            FROM Case_Communications__r) FROM Case WHERE Id = :testCase.Id];

        // Set the mock for the HTTP callout
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());

        // Call the getCaseDetails method with the test data
        Test.startTest();
        List<instaComponentController.instaWrapper> instaWrapperList = instaComponentController.getCaseDetails(CaseDetails.Id);
        instaComponentController.getUpdatedComments(testCase.Id);
        Test.stopTest();
    }
}