force-app/main/default/objects/Case/fields/Caption__c.field-meta.xml
<CustomField>
    <fullName>Caption__c</fullName>
    <label>Caption</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Case/fields/Case_Communication__c.field-meta.xml
<CustomField>
    <fullName>Case_Communication__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case Communication</label>
    <referenceTo>Case_Communication__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Post_Id__c.field-meta.xml
<CustomField>
    <fullName>Post_Id__c</fullName>
    <externalId>true</externalId>
    <label>Post Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case/fields/POST_URL__c.field-meta.xml
<CustomField>
    <fullName>POST_URL__c</fullName>
    <label>POST URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Case/fields/Type_of_Post__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Post__c</fullName>
    <label>Type of Post</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tags</fullName>
            </value>
            <value>
                <fullName>Mentions</fullName>
            </value>
            <value>
                <fullName>Hashtags</fullName>
            </value>
            <value>
                <fullName>Post</fullName>
            </value>
            <value>
                <fullName>DM</fullName>
            </value>
            <value>
                <fullName>Reel</fullName>
            </value>
            <value>
                <fullName>Comment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case_Communication__c/Case_Communication__c.object-meta.xml
<CustomObject>
    <label>Case Communication</label>
    <nameField>
        <displayFormat>CaseComm-{0000}</displayFormat>
        <label>Case Communication Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Communications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Communication__c/fields/Activity_Author__c.field-meta.xml
<CustomField>
    <fullName>Activity_Author__c</fullName>
    <label>Activity Author</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Communication__c/fields/Activity_Content__c.field-meta.xml
<CustomField>
    <fullName>Activity_Content__c</fullName>
    <label>Activity Content</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Case_Communication__c/fields/Activity_Created_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Activity_Created_DateTime__c</fullName>
    <label>Activity Created DateTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case_Communication__c/fields/Activity_ID__c.field-meta.xml
<CustomField>
    <fullName>Activity_ID__c</fullName>
    <externalId>true</externalId>
    <label>Activity ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case_Communication__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case Communications</relationshipLabel>
    <relationshipName>Case_Communications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Case_Communication__c/fields/Case_Communication__c.field-meta.xml
<CustomField>
    <fullName>Case_Communication__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case Communication</label>
    <referenceTo>Case_Communication__c</referenceTo>
    <relationshipLabel>Case Communications</relationshipLabel>
    <relationshipName>Case_Communications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case_Communication__c/fields/Platform_URL__c.field-meta.xml
<CustomField>
    <fullName>Platform_URL__c</fullName>
    <label>Activity Source URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Case_Communication__c/fields/Replied_Activities__c.field-meta.xml
<CustomField>
    <fullName>Replied_Activities__c</fullName>
    <label>Replied Activities</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Instagram_Api_Details__c/Instagram_Api_Details__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Instagram Api Details</label>
</CustomObject>

force-app/main/default/objects/Instagram_Api_Details__c/fields/accessToken__c.field-meta.xml
<CustomField>
    <fullName>accessToken__c</fullName>
    <label>User Access Token</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Instagram_Api_Details__c/fields/basicUrl__c.field-meta.xml
<CustomField>
    <fullName>basicUrl__c</fullName>
    <label>basicUrl</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Instagram_Api_Details__c/fields/businessUserId__c.field-meta.xml
<CustomField>
    <fullName>businessUserId__c</fullName>
    <label>businessUserId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Instagram_Api_Details__c/fields/REDIRECT_URI__c.field-meta.xml
<CustomField>
    <fullName>REDIRECT_URI__c</fullName>
    <label>REDIRECT_URI</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/instaComponentController.cls
/*
* Test Class name : instaComponentControllerTest
* created Date     : 29/07/2023
* Created By       : shubham kumar
* Last Modfied By  : shubham kumar
* Descritpion      : This class contains all the api's related to instagram.
*/
public class instaComponentController {
    
    //Getting the basic details from custom setting
    private static Instagram_Api_Details__c fap = Instagram_Api_Details__c.getInstance();
    
    private static final String CLIENT_ID        = fap.CLIENT_ID__c;
    private static String CLIENT_SECRET          = fap.CLIENT_SECRET__c;
    private static String REDIRECT_URI           = fap.REDIRECT_URI__c;
    private static String accessToken            = fap.accessToken__c;
    private static String basicUrl               = fap.basicUrl__c;
    private static String businessUserId         = fap.businessUserId__c;
    
    
 @AuraEnabled
    public Static List<ReplyWrapperRecords> getRepliesDetails(String commentId){
        List<ReplyWrapperRecords> repliesWrapperList = new List<ReplyWrapperRecords>();
        //List<ReplyWrapperRecords> replyDataList = new List<ReplyWrapperRecords>();
        List<Case_Communication__c> postCommentDetails = [Select Activity_Content__c,Activity_ID__c,Activity_Author__c,Platform_URL__c,Activity_Created_DateTime__c,Replied_Activities__c from Case_Communication__c where Activity_ID__c =:commentId];
        
        if(postCommentDetails.size() > 0){
            try{
                String jsonString = postCommentDetails[0].Replied_Activities__c;
                if(jsonString != null){
                    // Parse the JSON-like string
                    List<Map<String, String>> replyDataList = new List<Map<String, String>>();
                    Matcher matcher = Pattern.compile('\\[id=(\\d+), text=(.*?), timestamp=(.*?), username=(.*?)\\]').matcher(jsonString);
                    while (matcher.find()) {
                        Map<String, String> replyData = new Map<String, String>();
                        replyData.put('id', matcher.group(1));
                        replyData.put('text', matcher.group(2));
                        replyData.put('timestamp', matcher.group(3));
                        replyData.put('username', matcher.group(4));
                        replyDataList.add(replyData);
                    }
                    //List<ReplyWrapperRecords> wrapperRecordsList = new List<ReplyWrapperRecords>();
                    for (Map<String, String> replyData : replyDataList) {
                        ReplyWrapperRecords wrapperRecord = new ReplyWrapperRecords();
                        wrapperRecord.id = replyData.get('id');
                        wrapperRecord.text = replyData.get('text');
                        // Extract and format timestamp as needed
                        wrapperRecord.postDate = replyData.get('timestamp').split('T')[0].removeEnd('+0000');//Datetime.parse(replyData.get('timestamp')).format('yyyy-MM-dd');
                        wrapperRecord.postTime = replyData.get('timestamp').split('T')[1].removeEnd('+0000');//Datetime.parse(replyData.get('timestamp')).format('HH:mm:ss');
                        wrapperRecord.username = replyData.get('username');
                        repliesWrapperList.add(wrapperRecord);
                    }
                    return repliesWrapperList;
                }else{ 
                    return repliesWrapperList;  
                }
            }
            catch(exception e){
                system.debug('Error is '+e.getMessage());
                return repliesWrapperList;  
            }
        }else{
            
            return repliesWrapperList;  
        }
        
    }
    //This is being called on page load..
    @AuraEnabled
    public Static List<instaWrapper> getCaseDetails(String recordId){
        List<instaWrapper> instaWrapperList = new List<instaWrapper>();
        List<Case> CaseDetails = [Select id,subject,Post_Id__c,Description,Type_of_Post__c,Caption__c,POST_URL__c,
                                  (Select  Activity_ID__c,Activity_Created_DateTime__c,Activity_Content__c,Activity_Author__c,Platform_URL__c
                                    from Case_Communications__r ) from case where id = :recordId];
        
        for(Case caseRec : CaseDetails){
            try{
            if(caseRec.Case_Communications__r.size() > 0){
                for(Case_Communication__c pcRec : caseRec.Case_Communications__r ){
                        instaWrapper iw = new instaWrapper();
                        iw.comment = pcRec.Activity_Content__c;
                        iw.CommentedBy = pcRec.Activity_Author__c;
                        iw.PostUrl = pcRec.Platform_URL__c;
                        iw.CommentId = pcRec.Activity_ID__c;
                        iw.postDateTime = String.valueOf(pcRec.Activity_Created_DateTime__c);
                        iw.postType = caseRec.Type_of_Post__c;
                        iw.postCaption = caseRec.Description;
                        instaWrapperList.add(iw);
                    }
                }else{
                    instaWrapper iw = new instaWrapper();
                    iw.PostUrl = caseRec.POST_URL__c;
                    iw.postCaption = caseRec.Description;
                    iw.postType = caseRec.Type_of_Post__c;
                    instaWrapperList.add(iw);
                }
            }
             catch(exception e){
                system.debug('Error is '+e.getMessage());
                return instaWrapperList;  
            }
        }
        return instaWrapperList;
    }
    @AuraEnabled
    public Static Void getUpdatedComments(String recordId){
        system.debug('recordId=======>'+recordId);
        Case CaseRecord = [Select id , Post_Id__c from case where id = :recordId];
        List<instaWrapper> instaWrapperList = new List<instaWrapper>();
        InstagramUtilityClass.getMediaDetailsFromMediaId(CaseRecord.Post_Id__c);
        
    }
    @AuraEnabled
    public Static void replyToComment(String commentId,String commentMessage){
        system.debug('commentId'+commentId);
        system.debug('commentMessage'+commentMessage);
	
       
        commentMessage = EncodingUtil.urlEncode(commentMessage, 'UTF-8');
        commentMessage = commentMessage.replaceAll(' ','%20');
        commentMessage = commentMessage.replaceAll('<[^>]+>','');
       
        String endpointUrl = basicUrl+commentId+'/replies?message='+commentMessage;
        Map<String, String> queryParams = new Map<String, String>();
        Map<String, String> headers = new Map<String, String>{'Content-Type' => 'application/json','Authorization' => 'Bearer '+accessToken};
            HttpResponse response = DynamicHttpCallout.makeHttpPOSTCallout(endpointUrl, queryParams, headers);
        system.debug('Response==>'+response.getBody());
        // Process the response
        if (response.getStatusCode() == 200) {
            system.debug('The Response is ==>'+response.getBody());
        }else{
            system.debug('The Failed Response is ==>'+response.getBody());
        }   
    }
    
    public class instaWrapper{
        @AuraEnabled
        public String comment{get;set;}
        @AuraEnabled
        public String postDateTime{get;set;}
        @AuraEnabled
        public String postCaption{get;set;}
        @AuraEnabled
        public String postType{get;set;}
        @AuraEnabled
        public String CommentedBy {get;set;}
        @AuraEnabled
        public String PostUrl{get;set;}
        @AuraEnabled
        public String CommentId{get;set;}
    }
    
    public class ReplyWrapperRecords {
        @AuraEnabled
        public String id { get; set; }
        @AuraEnabled
        public String postDate { get; set; }
        @AuraEnabled
        public String postTime { get; set; }
        @AuraEnabled
        public String text { get; set; }
        @AuraEnabled
        public String username { get; set; }
    }
}