force-app/main/default/objects/Case/fields/Case_Reason_Description__c.field-meta.xml
<CustomField>
    <fullName>Case_Reason_Description__c</fullName>
    <label>Closure Remark</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Case/fields/Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Order_Number__c</fullName>
    <formula>OrderId__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Order Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Sub_Type__c</fullName>
    <label>Sub Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Order Related</fullName>
            </value>
            <value>
                <fullName>App Related</fullName>
            </value>
            <value>
                <fullName>Refund Issues</fullName>
            </value>
            <value>
                <fullName>Mobile number change</fullName>
            </value>
            <value>
                <fullName>Update Email id</fullName>
            </value>
            <value>
                <fullName>Process to add or update more addresses</fullName>
            </value>
            <value>
                <fullName>Product Price</fullName>
            </value>
            <value>
                <fullName>Comparison with Competitor</fullName>
            </value>
            <value>
                <fullName>Offers and Promotions</fullName>
            </value>
            <value>
                <fullName>Gift / Pre-book</fullName>
            </value>
            <value>
                <fullName>Process to Purchase / Delivery Charges</fullName>
            </value>
            <value>
                <fullName>Expected Delivery TAT / Preferred Delivery window</fullName>
            </value>
            <value>
                <fullName>Previous order OOS Req for benefit/code</fullName>
            </value>
            <value>
                <fullName>Missed campaign Req. for Benefit/code</fullName>
            </value>
            <value>
                <fullName>Word of Mouth on Order Cancellation</fullName>
            </value>
            <value>
                <fullName>Know more about products</fullName>
            </value>
            <value>
                <fullName>Product Suitability</fullName>
            </value>
            <value>
                <fullName>Product Quantity or Ingredients or Description</fullName>
            </value>
            <value>
                <fullName>Stock / Restock</fullName>
            </value>
            <value>
                <fullName>Product life /Expiry/Authencity /Others</fullName>
            </value>
            <value>
                <fullName>Collaboration Request/Influencer queries</fullName>
            </value>
            <value>
                <fullName>Collaboration service issues</fullName>
            </value>
            <value>
                <fullName>Collaboration Request</fullName>
            </value>
            <value>
                <fullName>Content Issues - Cx</fullName>
            </value>
            <value>
                <fullName>Content Issues - Partners</fullName>
            </value>
            <value>
                <fullName>Order Status</fullName>
            </value>
            <value>
                <fullName>Gift Before Shipping</fullName>
            </value>
            <value>
                <fullName>Gift After Shipping</fullName>
            </value>
            <value>
                <fullName>Cancellation Before Shipping</fullName>
            </value>
            <value>
                <fullName>Cancellation After Shipping</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Type_of_Call__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Call__c</fullName>
    <label>Type of Call</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Feedback</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/bulkCloseCasesController.cls
public class bulkCloseCasesController {
    @AuraEnabled
    
    public static List<Case> bulkCloseCasesMeth(){
        List<Case> CaseList = new List<Case>();
    try{
        
        CaseList = [Select Id,AccountId,CaseNumber,Order_Number__c,Account.Name,Subject,Type,Sub_Type__c,RecordType.Name,Origin,Status,Type_of_Call__c From Case WHERE RecordType.Name = 'Outbound Case'
        AND Origin = 'Bulk Upload' AND 	Status != 'Closed' AND Type_of_Call__c != 'Sales' ];
        
        System.debug('Number of Cases: ' + CaseList.size());
        System.debug('CaseList=======>'+CaseList);
    }
    Catch(Exception e){
         System.debug('Error =====>' + e.getMessage() + ' at Line Number====>' + e.getLineNumber());
    }
    return CaseList;
    }

    @AuraEnabled
    public static String updateCase(List<Case> caselist) {
        try {
            //List<String>closureRemark, List<String> casesIds
           // Set<Id> setOfCaseId = new Set<Id>();
            //List<Case> casesToUpdate = [SELECT Id, Case_Reason_Description__c,Status FROM Case WHERE Id IN :casesIds];
            //System.debug('casesToUpdate=========>' + casesToUpdate);
            if(!caselist.isEmpty()){
                for (Case cs : caselist) {
                   
                    cs.Status = 'Closed';
                    
                }
                update caselist;
                System.debug('caselist=======>'+caselist);
                return 'Success: Cases have been closed';
            } else {
                return 'No cases found to update.';
            }
        } catch (Exception e) {
            System.debug('Error: ' + e.getMessage() + ' at Line Number: ' + e.getLineNumber());
            return 'Error: ' + e.getMessage();
        }
    }



}