force-app/main/default/objects/Case/fields/Case_Communication__c.field-meta.xml
<CustomField>
    <fullName>Case_Communication__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case Communication</label>
    <referenceTo>Case_Communication__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/HashTag__c.field-meta.xml
<CustomField>
    <fullName>HashTag__c</fullName>
    <label>HashTag(#)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Post_Id__c.field-meta.xml
<CustomField>
    <fullName>Post_Id__c</fullName>
    <externalId>true</externalId>
    <label>Post Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Social_Media.recordType-meta.xml
<RecordType>
    <fullName>Social_Media</fullName>
    <active>true</active>
    <businessProcess>Support Processes</businessProcess>
    <label>Social Media</label>
</RecordType>

force-app/main/default/objects/Case_Communication__c/Case_Communication__c.object-meta.xml
<CustomObject>
    <label>Case Communication</label>
    <nameField>
        <displayFormat>CaseComm-{0000}</displayFormat>
        <label>Case Communication Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Communications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Communication__c/fields/Activity_Content__c.field-meta.xml
<CustomField>
    <fullName>Activity_Content__c</fullName>
    <label>Activity Content</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Case_Communication__c/fields/Activity_ID__c.field-meta.xml
<CustomField>
    <fullName>Activity_ID__c</fullName>
    <externalId>true</externalId>
    <label>Activity ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case_Communication__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case Communications</relationshipLabel>
    <relationshipName>Case_Communications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Case_Communication__c/fields/Case_Communication__c.field-meta.xml
<CustomField>
    <fullName>Case_Communication__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case Communication</label>
    <referenceTo>Case_Communication__c</referenceTo>
    <relationshipLabel>Case Communications</relationshipLabel>
    <relationshipName>Case_Communications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Instagram_Api_Details__c/Instagram_Api_Details__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Instagram Api Details</label>
</CustomObject>

force-app/main/default/objects/Instagram_Api_Details__c/fields/accessToken__c.field-meta.xml
<CustomField>
    <fullName>accessToken__c</fullName>
    <label>User Access Token</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Instagram_Api_Details__c/fields/basicUrl__c.field-meta.xml
<CustomField>
    <fullName>basicUrl__c</fullName>
    <label>basicUrl</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Instagram_Api_Details__c/fields/businessUserId__c.field-meta.xml
<CustomField>
    <fullName>businessUserId__c</fullName>
    <label>businessUserId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Instagram_Api_Details__c/fields/HashTag__c.field-meta.xml
<CustomField>
    <fullName>HashTag__c</fullName>
    <label>HashTag(#)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Instagram_Api_Details__c/fields/next_pagination_hashtag_Token__c.field-meta.xml
<CustomField>
    <fullName>next_pagination_hashtag_Token__c</fullName>
    <label>next pagination hashtag Token</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Instagram_Api_Details__c/fields/next_Pagination_Mention_Token__c.field-meta.xml
<CustomField>
    <fullName>next_Pagination_Mention_Token__c</fullName>
    <label>next Pagination Mention Token</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Instagram_Api_Details__c/fields/next_Pagination_Post_Token__c.field-meta.xml
<CustomField>
    <fullName>next_Pagination_Post_Token__c</fullName>
    <label>next Pagination Post Token</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Instagram_Api_Details__c/fields/REDIRECT_URI__c.field-meta.xml
<CustomField>
    <fullName>REDIRECT_URI__c</fullName>
    <label>REDIRECT_URI</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/InstagramPostCreationBatchTest.cls
@isTest
public class InstagramPostCreationBatchTest {
    @isTest
    static void testBatchExecution() {
        RecordType caseRecordType;
        try {
            caseRecordType = [SELECT Id FROM RecordType WHERE SObjectType = 'Case' AND DeveloperName = 'Social_Media' LIMIT 1];
        } catch (Exception e) {
            System.debug('RecordType not found: ' + e.getMessage());
            return;
        }

        // Create Instagram API details record
        Instagram_Api_Details__c fap = new Instagram_Api_Details__c();
        fap.CLIENT_ID__c = 'bccbckbcewbcje';
        fap.CLIENT_SECRET__c = 'cbewciuewcw cweu ciw cwucw';
        fap.REDIRECT_URI__c = 'bcewcbwecwueicwc c iwcw';
        fap.accessToken__c = 'bxiueqbcubce ccwebcw cuew';
        fap.basicUrl__c = 'bcwiuecewucwcuew cew cw cweuc';
        fap.businessUserId__c = 'bcew ciwu ce ce cuec';
        fap.next_Pagination_Post_Token__c = 'ncencencienciencnecne';
        fap.next_Pagination_Mention_Token__c = 'uebfbbcuebcebcucbeubcuecue';
        fap.next_pagination_hashtag_Token__c = 'jciece ci c e ce c';
        fap.HashTag__c = 'ubcebwcubcuewcubcuewbcbew'; 
        insert fap;
        
        // Create a test Case record
        Case testCase = new Case(
            Subject = 'Test Case',
            Origin = 'Instagram',
            RecordTypeId = caseRecordType.Id,
            Brand__c = 'Hyphen',
            Post_Id__c = '17841405793087218'
        );
        insert testCase;
        
        // Create a test Case_Communication__c record
        Case_Communication__c testComment = new Case_Communication__c(
            Case__c = testCase.Id,
            Activity_Content__c = 'Test comment',
            Activity_ID__c = 'test_comment_id_123'
        );
        insert testComment;
        
        // Start the batch process
        Test.startTest();
        InstagramPostCreationBatch batch = new InstagramPostCreationBatch();
        Database.executeBatch(batch);
        Test.stopTest();
        
        // Perform assertions to verify the expected results
        // For example, check if the inserted Case records and Case_Communication__c records are as expected
    }
}