force-app/main/default/objects/Case/fields/Case_Sub_Status__c.field-meta.xml
<CustomField>
    <fullName>Case_Sub_Status__c</fullName>
    <label>Case Sub-Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Assigned to CS Team</fullName>
            </value>
            <value>
                <fullName>Assigned to Warehouse Team</fullName>
            </value>
            <value>
                <fullName>Assigned to Refund Team</fullName>
            </value>
            <value>
                <fullName>Assigned to Marketing Team</fullName>
            </value>
            <value>
                <fullName>Referred Back to CS Team</fullName>
            </value>
            <value>
                <fullName>Closed as Duplicate Case</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/CS_Team_Member__c.field-meta.xml
<CustomField>
    <fullName>CS_Team_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CS Team Member</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Cases3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Marketing__c.field-meta.xml
<CustomField>
    <fullName>Marketing__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Marketing</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Marketing_Team__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Marketing Team Member</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Cases1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/MT_Assignment_Reason__c.field-meta.xml
<CustomField>
    <fullName>MT_Assignment_Reason__c</fullName>
    <label>Re-Assignment Reason</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/MT_Assignment_Remarks__c.field-meta.xml
<CustomField>
    <fullName>MT_Assignment_Remarks__c</fullName>
    <label>MT Assignment Remarks</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Case/fields/OrderId__c.field-meta.xml
<CustomField>
    <fullName>OrderId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Order.Name</field>
            <operation>notContain</operation>
            <value>-</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Sub_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Sub_Sub_Type__c</fullName>
    <label>Sub Sub Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sub_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Login issues/Login number error</fullName>
            </value>
            <value>
                <fullName>Invalid Email/Phone Number</fullName>
            </value>
            <value>
                <fullName>Invalid Coupon Code</fullName>
            </value>
            <value>
                <fullName>App Stuck or Hanged</fullName>
            </value>
            <value>
                <fullName>Error while adding in cart</fullName>
            </value>
            <value>
                <fullName>Product Description/Offer Issues</fullName>
            </value>
            <value>
                <fullName>Addition of More Payment options or COD</fullName>
            </value>
            <value>
                <fullName>Refund Issues</fullName>
            </value>
            <value>
                <fullName>Change in profile number</fullName>
            </value>
            <value>
                <fullName>Updation of new email id</fullName>
            </value>
            <value>
                <fullName>Change in mail id</fullName>
            </value>
            <value>
                <fullName>Process to add/update more addresses</fullName>
            </value>
            <value>
                <fullName>Guided on App</fullName>
            </value>
            <value>
                <fullName>Price mismatch</fullName>
            </value>
            <value>
                <fullName>Comparison with Competitor</fullName>
            </value>
            <value>
                <fullName>Ongoing Campaign/Sales updates</fullName>
            </value>
            <value>
                <fullName>Upcoming Campaign /Sales updates</fullName>
            </value>
            <value>
                <fullName>How to check product review</fullName>
            </value>
            <value>
                <fullName>Giveaway inquiry</fullName>
            </value>
            <value>
                <fullName>Use of Coupon codes</fullName>
            </value>
            <value>
                <fullName>Coupon/Freebie /Discount/Cashback Issuance</fullName>
            </value>
            <value>
                <fullName>Gift an Order</fullName>
            </value>
            <value>
                <fullName>Information Given</fullName>
            </value>
            <value>
                <fullName>Guided to explore personalization on app</fullName>
            </value>
            <value>
                <fullName>Collabration Request/Influencer queries</fullName>
            </value>
            <value>
                <fullName>Collabration service issues</fullName>
            </value>
            <value>
                <fullName>Collabration Request</fullName>
            </value>
            <value>
                <fullName>Content Issues - Cx</fullName>
            </value>
            <value>
                <fullName>Content Issues - Partners</fullName>
            </value>
            <value>
                <fullName>Order number confirmation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Sub_Type__c</fullName>
    <label>Sub Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Order Related</fullName>
            </value>
            <value>
                <fullName>App Related</fullName>
            </value>
            <value>
                <fullName>Refund Issues</fullName>
            </value>
            <value>
                <fullName>Mobile number change</fullName>
            </value>
            <value>
                <fullName>Update Email id</fullName>
            </value>
            <value>
                <fullName>Process to add or update more addresses</fullName>
            </value>
            <value>
                <fullName>Product Price</fullName>
            </value>
            <value>
                <fullName>Comparison with Competitor</fullName>
            </value>
            <value>
                <fullName>Offers and Promotions</fullName>
            </value>
            <value>
                <fullName>Gift / Pre-book</fullName>
            </value>
            <value>
                <fullName>Process to Purchase / Delivery Charges</fullName>
            </value>
            <value>
                <fullName>Expected Delivery TAT / Preferred Delivery window</fullName>
            </value>
            <value>
                <fullName>Previous order OOS Req for benefit/code</fullName>
            </value>
            <value>
                <fullName>Missed campaign Req. for Benefit/code</fullName>
            </value>
            <value>
                <fullName>Word of Mouth on Order Cancellation</fullName>
            </value>
            <value>
                <fullName>Know more about products</fullName>
            </value>
            <value>
                <fullName>Product Suitability</fullName>
            </value>
            <value>
                <fullName>Product Quantity or Ingredients or Description</fullName>
            </value>
            <value>
                <fullName>Stock / Restock</fullName>
            </value>
            <value>
                <fullName>Product life /Expiry/Authencity /Others</fullName>
            </value>
            <value>
                <fullName>Collaboration Request/Influencer queries</fullName>
            </value>
            <value>
                <fullName>Collaboration service issues</fullName>
            </value>
            <value>
                <fullName>Collaboration Request</fullName>
            </value>
            <value>
                <fullName>Content Issues - Cx</fullName>
            </value>
            <value>
                <fullName>Content Issues - Partners</fullName>
            </value>
            <value>
                <fullName>Order Status</fullName>
            </value>
            <value>
                <fullName>Gift Before Shipping</fullName>
            </value>
            <value>
                <fullName>Gift After Shipping</fullName>
            </value>
            <value>
                <fullName>Cancellation Before Shipping</fullName>
            </value>
            <value>
                <fullName>Cancellation After Shipping</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/marketingTeamCaseController.cls
public without sharing class marketingTeamCaseController {

    @AuraEnabled
    public Static Case marketingTeamCase(String recId) {
        return [SELECT Id, CaseNumber, Account.Name, OrderId__c,OrderId__r.OrderNumber,Subject,MT_Assignment_Reason__c,MT_Assignment_Remarks__c, RecordType.Name,CreatedBy.Name, Sub_Type__c, Sub_Sub_Type__c FROM Case WHERE Id = :recId LIMIT 1];
       
        
    }
    @AuraEnabled
    public static List<User> getUsersByProfileName() {
        List<User> users = [SELECT Id, Name FROM User WHERE Profile.Name = 'Marketing Team'];       
        System.debug('users=====>'+users);
        return users;
    }

    @AuraEnabled
    public static String userUpdate(String recId, String UserName, String MarketingReason) {
        System.debug('recId=====>' + recId);
        System.debug('UserName=====>' + UserName);
        System.debug('MarketingReason=====>' + MarketingReason);
        try {
            Set<Id> setOfOwnerId = new Set<Id>();
            List<Case> caseList1 = [SELECT Id, OwnerId, Owner.Email, Owner.Name, ContactId, Contact.Email, CreatedDate, CaseNumber, CS_Team_Member__c FROM Case WHERE Id =:recId];
            Case cs = new Case();
            if(!caseList1.isEmpty()){
                cs = caseList1[0];
            }
            if(cs.CS_Team_Member__c == null){
                cs.CS_Team_Member__c = cs.OwnerId;
            }
            String CSteamId = cs.CS_Team_Member__c;
            //cs.Marketing_Team__c = UserName;
            cs.OwnerId = UserName;
            cs.MT_Assignment_Reason__c = MarketingReason;
            cs.Marketing__c = true;
            cs.Status = 'In Progress';
            cs.Case_Sub_Status__c = 'Assigned to Marketing Team';
            update cs;
            System.debug('cs ==>'+cs);
        
            setOfOwnerId.add(caseList1[0].OwnerId);
            System.debug('caseList=====>' + caseList1);

            List<CaseShare> existingShares = [SELECT Id FROM CaseShare WHERE CaseId = :cs.Id AND UserOrGroupId = :CSteamId];
                System.debug('existingShares======>'+existingShares);

                if(!existingShares.isEmpty()){
                    //delete existingShares;
                    System.debug('existingShares delete records======>'+existingShares);
                }else{
                    CaseShare newCaseShare = new CaseShare();
                    newCaseShare.CaseId =  cs.Id;    //caseRecord.Id;
                    //System.debug('caseId=======>'+caseId);      
                    newCaseShare.UserOrGroupId = CSteamId;
                    //System.debug('CSteamId=====>'+CSteamId);
                    newCaseShare.CaseAccessLevel = 'Edit';
                    //newCaseShare.RowCause = Schema.CaseShare.RowCause.Manual;
                    insert newCaseShare;
                    System.debug('newCaseShare======>'+newCaseShare);
                }
    
            Map<Id, Contact> mapOfContact = new Map<Id, Contact>();
            Set<Id> setOfContactId = new Set<Id>();
            if (!caseList1.isEmpty()) {
                for (Case cse : caseList1) {
                    setOfContactId.add(cse.ContactId);
                }
            }
            System.debug('setOfContactId ==>'+setOfContactId);
            List<Contact> conlist = [SELECT Id, Name, Phone, Email FROM Contact WHERE Id IN :setOfContactId];
            System.debug('conlist=====>' + conlist);
            if (!conlist.isEmpty()) {
                for (Contact Con : conlist) {
                    mapOfContact.put(Con.Id, Con);
                }
            }
    
            List<User> useList = [SELECT Id, Name,Email FROM User WHERE Id IN :setOfOwnerId];
            System.debug('useList=====>' + useList);
            Set<String> marketingTeamUsers = new Set<String>();
            List<Id> marketingTeamTaskUsers = new List<Id>();
            for (User usr : useList) {
                marketingTeamUsers.add(usr.Id);
                marketingTeamTaskUsers.add(usr.Id);
            }
            System.debug('marketingTeamUsers=====>' + marketingTeamUsers);
            System.debug('marketingTeamTaskUsers=====>' + marketingTeamTaskUsers);
    
            EmailTemplate temp = [SELECT Id, Name, DeveloperName, Subject, Body, HTMLValue FROM EmailTemplate WHERE DeveloperName = 'email_to_customer_on_marketing_team'];
            System.debug('temp=====>' + temp);
    
            List<CustomNotificationType> TemplateInfoDetail = [SELECT Id, DeveloperName FROM CustomNotificationType WHERE DeveloperName = 'custom_notification_to_refund_team_on_pincode_not_serviceable'];
            System.debug('TemplateInfoDetail=====>' + TemplateInfoDetail);
    
            List<Messaging.SingleEmailMessage> mailList = new List<Messaging.SingleEmailMessage>();
            //List<Messaging.CustomNotification> notificationList = new List<Messaging.CustomNotification>();
    
            String str = temp.HTMLValue;
            String body = temp.body;
            List<Task> taskList = new List<Task>();
            List<Case> caseListToBeUpdated = new List<Case>();
            List<String> emailString = new List<String>();
            for (Case cse : caseList1) {
    
                Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                Messaging.CustomNotification notification = new Messaging.CustomNotification();
    
                if (cse.Owner.Name != null) {
                    body = body.replace('{!Case.Contact}', cse.Owner.Name);
                }
                if (cse.ContactId != null) {
                    body = body.replace('{!Case.Contact}', mapOfContact.get(cse.ContactId).Name);
                }
                if (cse.CaseNumber != null) {
                    body = body.replace('{!Case.CaseNumber}', String.ValueOf(cse.CaseNumber));
                }
    
                emailString.add(cse.Owner.Email);
                System.debug('emailString===>' + emailString);
                mail.setSubject(temp != null ? temp.Subject : '');
                mail.setPlainTextBody(body);
                mail.setTemplateId(temp != null ? temp.Id : null);
                mail.setSaveAsActivity(true);
                mail.setWhatId(cse.Id);
                mail.setToAddresses(emailString);
                mailList.add(mail);
    
                // notification.setBody('A new Case Has been Assigned to you Please go through it and resolve it ASAP');
                // notification.setTitle('Assigned To Marketing Team');
                // notification.setSenderId(UserInfo.getUserId());
                // notification.setNotificationTypeId(TemplateInfoDetail[0].Id);
                // notification.setTargetId(cse.Id);
                // notification.send(marketingTeamUsers);
    
                Task tsk = new Task();
                tsk.Subject = 'Resolve the Case as early as Possible';
                tsk.Priority = 'High';
                tsk.ActivityDate = System.today().addDays(2);
                tsk.WhatId = cse.Id;
                tsk.OwnerId = marketingTeamTaskUsers[0];
                taskList.add(tsk);
                System.debug('tsk ==>'+tsk);
            }
            Insert taskList;
            if (!mailList.isEmpty()) {
                Messaging.sendEmail(mailList);
            }
    
            return 'SUCCESS';
        } catch (Exception e) {
            System.debug('Error == >' + e.getMessage() + ' && Error Line == >' + e.getLineNumber());
        }
        return null;
    }
    
}