force-app/main/default/objects/Case/fields/Coupon__c.field-meta.xml
<CustomField>
    <fullName>Coupon__c</fullName>
    <label>Coupon</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Order_Date__c.field-meta.xml
<CustomField>
    <fullName>Order_Date__c</fullName>
    <formula>OrderId__r.EffectiveDate</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Order Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/OrderId__c.field-meta.xml
<CustomField>
    <fullName>OrderId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Order.Name</field>
            <operation>notContain</operation>
            <value>-</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Refund_Reason__c.field-meta.xml
<CustomField>
    <fullName>Refund_Reason__c</fullName>
    <label>Refund Reason</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Case/fields/Refund_Type__c.field-meta.xml
<CustomField>
    <fullName>Refund_Type__c</fullName>
    <label>Refund Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Partial</fullName>
            </value>
            <value>
                <fullName>Full</fullName>
            </value>
            <value>
                <fullName>Special Case Refund</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Sub_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Sub_Sub_Type__c</fullName>
    <label>Sub Sub Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sub_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Login issues/Login number error</fullName>
            </value>
            <value>
                <fullName>Invalid Email/Phone Number</fullName>
            </value>
            <value>
                <fullName>Invalid Coupon Code</fullName>
            </value>
            <value>
                <fullName>App Stuck or Hanged</fullName>
            </value>
            <value>
                <fullName>Error while adding in cart</fullName>
            </value>
            <value>
                <fullName>Product Description/Offer Issues</fullName>
            </value>
            <value>
                <fullName>Addition of More Payment options or COD</fullName>
            </value>
            <value>
                <fullName>Refund Issues</fullName>
            </value>
            <value>
                <fullName>Change in profile number</fullName>
            </value>
            <value>
                <fullName>Updation of new email id</fullName>
            </value>
            <value>
                <fullName>Change in mail id</fullName>
            </value>
            <value>
                <fullName>Process to add/update more addresses</fullName>
            </value>
            <value>
                <fullName>Guided on App</fullName>
            </value>
            <value>
                <fullName>Price mismatch</fullName>
            </value>
            <value>
                <fullName>Comparison with Competitor</fullName>
            </value>
            <value>
                <fullName>Ongoing Campaign/Sales updates</fullName>
            </value>
            <value>
                <fullName>Upcoming Campaign /Sales updates</fullName>
            </value>
            <value>
                <fullName>How to check product review</fullName>
            </value>
            <value>
                <fullName>Giveaway inquiry</fullName>
            </value>
            <value>
                <fullName>Use of Coupon codes</fullName>
            </value>
            <value>
                <fullName>Coupon/Freebie /Discount/Cashback Issuance</fullName>
            </value>
            <value>
                <fullName>Gift an Order</fullName>
            </value>
            <value>
                <fullName>Information Given</fullName>
            </value>
            <value>
                <fullName>Guided to explore personalization on app</fullName>
            </value>
            <value>
                <fullName>Collabration Request/Influencer queries</fullName>
            </value>
            <value>
                <fullName>Collabration service issues</fullName>
            </value>
            <value>
                <fullName>Collabration Request</fullName>
            </value>
            <value>
                <fullName>Content Issues - Cx</fullName>
            </value>
            <value>
                <fullName>Content Issues - Partners</fullName>
            </value>
            <value>
                <fullName>Order number confirmation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Sub_Type__c</fullName>
    <label>Sub Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Order Related</fullName>
            </value>
            <value>
                <fullName>App Related</fullName>
            </value>
            <value>
                <fullName>Refund Issues</fullName>
            </value>
            <value>
                <fullName>Mobile number change</fullName>
            </value>
            <value>
                <fullName>Update Email id</fullName>
            </value>
            <value>
                <fullName>Process to add or update more addresses</fullName>
            </value>
            <value>
                <fullName>Product Price</fullName>
            </value>
            <value>
                <fullName>Comparison with Competitor</fullName>
            </value>
            <value>
                <fullName>Offers and Promotions</fullName>
            </value>
            <value>
                <fullName>Gift / Pre-book</fullName>
            </value>
            <value>
                <fullName>Process to Purchase / Delivery Charges</fullName>
            </value>
            <value>
                <fullName>Expected Delivery TAT / Preferred Delivery window</fullName>
            </value>
            <value>
                <fullName>Previous order OOS Req for benefit/code</fullName>
            </value>
            <value>
                <fullName>Missed campaign Req. for Benefit/code</fullName>
            </value>
            <value>
                <fullName>Word of Mouth on Order Cancellation</fullName>
            </value>
            <value>
                <fullName>Know more about products</fullName>
            </value>
            <value>
                <fullName>Product Suitability</fullName>
            </value>
            <value>
                <fullName>Product Quantity or Ingredients or Description</fullName>
            </value>
            <value>
                <fullName>Stock / Restock</fullName>
            </value>
            <value>
                <fullName>Product life /Expiry/Authencity /Others</fullName>
            </value>
            <value>
                <fullName>Collaboration Request/Influencer queries</fullName>
            </value>
            <value>
                <fullName>Collaboration service issues</fullName>
            </value>
            <value>
                <fullName>Collaboration Request</fullName>
            </value>
            <value>
                <fullName>Content Issues - Cx</fullName>
            </value>
            <value>
                <fullName>Content Issues - Partners</fullName>
            </value>
            <value>
                <fullName>Order Status</fullName>
            </value>
            <value>
                <fullName>Gift Before Shipping</fullName>
            </value>
            <value>
                <fullName>Gift After Shipping</fullName>
            </value>
            <value>
                <fullName>Cancellation Before Shipping</fullName>
            </value>
            <value>
                <fullName>Cancellation After Shipping</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/UTR_Number__c.field-meta.xml
<CustomField>
    <fullName>UTR_Number__c</fullName>
    <label>UTR Number</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OOSHelper.cls
public class OOSHelper {
    @AuraEnabled
    public static oosWrapper getCaseAndOrderDetails(String caseId){
        try{
            if(String.isNotBlank(caseId)){
                oosWrapper oosWr = new oosWrapper();
                Case caseRec = [SELECT Id, Sub_Type__c, Sub_Sub_Type__c, CaseNumber, OrderId__r.OrderNumber,OrderId__r.Status, OrderId__c, Order_Date__c, Status, ContactId, Contact.Email FROM Case WHERE Id =: caseId LIMIT 1];
                oosWr.caseRec = caseRec;
                if(caseRec.OrderId__c != null){
                    List<OrderItem> oliList = [SELECT Id, Product2.Name, Quantity, TotalPrice, OrderID, OriginalOrderItemId, Is_Duplicate_Order__c, PricebookEntryId,
                                               Product2Id, ListPrice, UnitPrice, Refund_Quantity__c FROM OrderItem WHERE OrderID =: caseRec.OrderId__c];
                    if(oliList.size()>0){
                        oosWr.oliList = oliList;
                    }
                }
                return oosWr;
            }
            return null;
        }catch(exception e){
            System.debug('Error Message==> ' + e.getMessage() + ' at Line Number==> ' + e.getLineNumber());
            return null;
        }
    }
    
    @AuraEnabled
    public static void createDupOrder(List<OrderItem> oliList, String caseId, Case caseRec){
        try{
            update caseRec;
            System.debug('caseRec==> ' + caseRec);
            String orderId = oliList[0].OrderID;
            Order orderRec = [SELECT Id, OwnerId, ContractId, AccountId, Pricebook2Id, OriginalOrderId, OpportunityId, QuoteId, EffectiveDate, EndDate, IsReductionOrder, Status, Description,
                              CustomerAuthorizedById, CustomerAuthorizedDate, CompanyAuthorizedById, CompanyAuthorizedDate, Type, BillingStreet, BillingCity, BillingState, BillingPostalCode,
                              BillingCountry, BillingLatitude, BillingLongitude, BillingGeocodeAccuracy, BillingAddress, ShippingStreet, ShippingCity, ShippingState, ShippingPostalCode, 
                              ShippingCountry, ShippingLatitude, ShippingLongitude, ShippingGeocodeAccuracy, ShippingAddress, Name, PoDate, PoNumber, OrderReferenceNumber, BillToContactId, 
                              ShipToContactId, ActivatedDate, ActivatedById, StatusCode, OrderNumber, TotalAmount, Refund_Amount__c, Case__c, Refund_Type__c, Refund_Reason__c, Coupon__c, 
                              Mobile_No__c, UTR_Number__c FROM Order WHERE Id =: orderId LIMIT 1];
            Order orderRecNew = new Order();
            orderRecNew = orderRec;
            orderRecNew.Id = null;
            orderRecNew.Case__c = caseId;
            orderRecNew.Is_Duplicate_Order__c = true;
            orderRecNew.ParentOrder__c = orderId;
            insert orderRecNew;
            System.debug('orderRecNew==> ' + orderRecNew);
            for(OrderItem oliRec : oliList){
                oliRec.OrderId = orderRecNew.Id;
            }
            insert oliList;
            System.debug('oliList==> ' + oliList);
            // EmailTemplate et = [SELECT Id, Name, DeveloperName, NamespacePrefix, OwnerId, FolderId, FolderName, BrandTemplateId, EnhancedLetterheadId, TemplateStyle, IsActive, 
            //                     TemplateType, Encoding, Description, Subject, HtmlValue, Body FROM EmailTemplate WHERE DeveloperName = 'Duplicate_Order_Creation_OOS'];
            // Messaging.SingleEmailMessage message = new        Messaging.SingleEmailMessage();
            // message.setTargetObjectId(caseRec.Id); 
            // message.setSenderDisplayName('Kult Kare Support'); 
            // message.setReplyTo('no-reply@company.com');
            // message.setUseSignature(false); 
            // message.setBccSender(false); 
            // message.setSaveAsActivity(true); 
            // message.setTemplateID(et.Id); 
            // message.setWhatId(CaseRec.ContactId);
            // message.toAddresses = new String[] { CaseRec.contact.email};
            //     Messaging.SingleEmailMessage[] messages = new List<Messaging.SingleEmailMessage> {message};
            //         Messaging.SendEmailResult[] results = Messaging.sendEmail(messages);
            // if (results[0].success) 
            // {
            //     System.debug('The email was sent successfully.');
            // } else {
            //     System.debug('The email failed to send: ' +  results[0].errors[0].message);
            // }
        }catch(exception e){
            System.debug('Error Message==> ' + e.getMessage() + ' at Line Number==> ' + e.getLineNumber());
        }
    }
    
    public class oosWrapper{
        @AuraEnabled
        public case caseRec;
        @AuraEnabled
        public List<OrderItem> oliList;
    }
}