force-app/main/default/objects/Case/fields/isFollowUp__c.field-meta.xml
<CustomField>
    <fullName>isFollowUp__c</fullName>
    <label>isFollowUp</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Follow_Up_Request__c/Follow_Up_Request__c.object-meta.xml
<CustomObject>
    <label>Follow Up Request</label>
    <nameField>
        <displayFormat>FUP-{0000}</displayFormat>
        <label>Follow Up Requests Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Follow Up Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Follow_Up_Request__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Follow Up Requests</relationshipLabel>
    <relationshipName>Follow_Up_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Follow_Up_Request__c/fields/Follow_Up_Status__c.field-meta.xml
<CustomField>
    <fullName>Follow_Up_Status__c</fullName>
    <label>Follow Up Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Responded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/followUpTriggerHelper.cls
public class followUpTriggerHelper {
    public static void updateCaseOnFollowUpCreation(List<Follow_Up_Request__c> followUpRequestList){
        Set<Id> setOfCaseId = new Set<Id>();
        for(Follow_Up_Request__c fur :followUpRequestList){
            if(fur.Case__c != null){
                setOfCaseId.add(fur.Case__c);
            }
        }
        
        List<Case> cseList = [SELECT Id,isFollowUp__c From Case Where Id IN: setOfCaseId];
        if(!cseList.isEmpty()){
            for(Case cs : cseList){
                cs.isFollowUp__c = 'Yes';
            }
            update cseList;
        }
    }
    
    public static void updateCaseOnFollowUpUpdation(List<Follow_Up_Request__c> followUpRequestList) {
        Set<Id> setOfCaseId = new Set<Id>();
        
        for (Follow_Up_Request__c fur : followUpRequestList) {
            if (fur.Case__c != null) {
                setOfCaseId.add(fur.Case__c);
            }
        }
        
        List<Follow_Up_Request__c> followUpReqList = [
            SELECT Id, Name, Case__c, Follow_Up_Status__c
            FROM Follow_Up_Request__c
            WHERE Case__c IN :setOfCaseId
            ORDER BY CreatedDate DESC LIMIT 1
        ];
        
        if (!followUpReqList.isEmpty()) {
            Follow_Up_Request__c recentFollowUp = followUpReqList[0];
            if (recentFollowUp.Follow_Up_Status__c == 'Responded') {
                Case cs = new Case();
                cs.Id = recentFollowUp.Case__c;
                cs.isFollowUp__c = 'No';
                
                update cs;
            }
        }
        
        
    }
    
}