force-app/main/default/objects/Case/fields/Marketing_Team__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Marketing Team Member</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Cases1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/OOS_Quantity__c.field-meta.xml
<CustomField>
    <fullName>OOS_Quantity__c</fullName>
    <label>OOS Quantity</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/OrderId__c.field-meta.xml
<CustomField>
    <fullName>OrderId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Order.Name</field>
            <operation>notContain</operation>
            <value>-</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/RefundTeamMember__c.field-meta.xml
<CustomField>
    <fullName>RefundTeamMember__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Refund Team Member</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/SKU_Details__c.field-meta.xml
<CustomField>
    <fullName>SKU_Details__c</fullName>
    <label>SKU Details</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Warehouse_Team_Member__c.field-meta.xml
<CustomField>
    <fullName>Warehouse_Team_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Warehouse Team Member</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Cases2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/createdAffectedSKUsTesr.cls
@isTest(seeAllData = true)
public class createdAffectedSKUsTesr {
    @isTest
    static void testResetTypeAndSubtypeOnRecordTypeChange1() { 
        User use = [SELECt Id,Name FRom User LIMIT 1];
        Order ord = [SELECT Id FROM Order LIMIT 1];
        Account acc = new Account(Name = 'Testing', Phone = '098765432123456');
        insert acc;
        
        Contact con = new Contact(AccountId = acc.Id, Email = 'new@contact.com', FirstName = 'Test', LastName = 'contact');
        insert con;
        
        
        Product2 objProduct = new Product2(Name = 'TestProduct', Description = 'Test Description');
        insert objProduct;
        
        PriceBook2 pb2Standard = [SELECT Id FROM Pricebook2 WHERE IsStandard = true LIMIT 1];
        Id standardPriceBookId = pb2Standard.Id;
        
        PricebookEntry objPBEntry = new PricebookEntry(Pricebook2Id = standardPriceBookId, Product2Id = objProduct.Id, UnitPrice = 100, IsActive = true);
        insert objPBEntry;
        
        Order testOrder = new Order(Name = 'TestOrder001',ParentOrder__c=ord.id, AccountId = acc.Id, Status = 'Draft', EffectiveDate = System.today(), Pricebook2Id = standardPriceBookId);
        insert testOrder;
        
        Case cse = new Case(Marketing_Team__c	 = use.id,Warehouse_Team_Member__c	=use.id,RefundTeamMember__c=use.id,Origin = 'Bulk Upload',SKU_Details__c='Test1',OOS_Quantity__c ='2', Status = 'New', AccountId = acc.Id, ContactId = con.Id, OwnerId = use.Id,OrderId__c=testOrder.id);
        insert cse;
        
      //  OrderItem orderItem = new OrderItem( Quantity = 1,OrderId=cse.Order__c, UnitPrice = 100.00, SKU__c = 'SKU001', PricebookEntryId = objPBEntry.Id,Is_Already_Utilized__c = False,Refund_Price__c = 123);
      //  insert orderItem;
    }
}