force-app/main/default/objects/Case/fields/OrderId__c.field-meta.xml
<CustomField>
    <fullName>OrderId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Order.Name</field>
            <operation>notContain</operation>
            <value>-</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Sub_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Sub_Sub_Type__c</fullName>
    <label>Sub Sub Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sub_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Login issues/Login number error</fullName>
            </value>
            <value>
                <fullName>Invalid Email/Phone Number</fullName>
            </value>
            <value>
                <fullName>Invalid Coupon Code</fullName>
            </value>
            <value>
                <fullName>App Stuck or Hanged</fullName>
            </value>
            <value>
                <fullName>Error while adding in cart</fullName>
            </value>
            <value>
                <fullName>Product Description/Offer Issues</fullName>
            </value>
            <value>
                <fullName>Addition of More Payment options or COD</fullName>
            </value>
            <value>
                <fullName>Refund Issues</fullName>
            </value>
            <value>
                <fullName>Change in profile number</fullName>
            </value>
            <value>
                <fullName>Updation of new email id</fullName>
            </value>
            <value>
                <fullName>Change in mail id</fullName>
            </value>
            <value>
                <fullName>Process to add/update more addresses</fullName>
            </value>
            <value>
                <fullName>Guided on App</fullName>
            </value>
            <value>
                <fullName>Price mismatch</fullName>
            </value>
            <value>
                <fullName>Comparison with Competitor</fullName>
            </value>
            <value>
                <fullName>Ongoing Campaign/Sales updates</fullName>
            </value>
            <value>
                <fullName>Upcoming Campaign /Sales updates</fullName>
            </value>
            <value>
                <fullName>How to check product review</fullName>
            </value>
            <value>
                <fullName>Giveaway inquiry</fullName>
            </value>
            <value>
                <fullName>Use of Coupon codes</fullName>
            </value>
            <value>
                <fullName>Coupon/Freebie /Discount/Cashback Issuance</fullName>
            </value>
            <value>
                <fullName>Gift an Order</fullName>
            </value>
            <value>
                <fullName>Information Given</fullName>
            </value>
            <value>
                <fullName>Guided to explore personalization on app</fullName>
            </value>
            <value>
                <fullName>Collabration Request/Influencer queries</fullName>
            </value>
            <value>
                <fullName>Collabration service issues</fullName>
            </value>
            <value>
                <fullName>Collabration Request</fullName>
            </value>
            <value>
                <fullName>Content Issues - Cx</fullName>
            </value>
            <value>
                <fullName>Content Issues - Partners</fullName>
            </value>
            <value>
                <fullName>Order number confirmation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Sub_Type__c</fullName>
    <label>Sub Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Order Related</fullName>
            </value>
            <value>
                <fullName>App Related</fullName>
            </value>
            <value>
                <fullName>Refund Issues</fullName>
            </value>
            <value>
                <fullName>Mobile number change</fullName>
            </value>
            <value>
                <fullName>Update Email id</fullName>
            </value>
            <value>
                <fullName>Process to add or update more addresses</fullName>
            </value>
            <value>
                <fullName>Product Price</fullName>
            </value>
            <value>
                <fullName>Comparison with Competitor</fullName>
            </value>
            <value>
                <fullName>Offers and Promotions</fullName>
            </value>
            <value>
                <fullName>Gift / Pre-book</fullName>
            </value>
            <value>
                <fullName>Process to Purchase / Delivery Charges</fullName>
            </value>
            <value>
                <fullName>Expected Delivery TAT / Preferred Delivery window</fullName>
            </value>
            <value>
                <fullName>Previous order OOS Req for benefit/code</fullName>
            </value>
            <value>
                <fullName>Missed campaign Req. for Benefit/code</fullName>
            </value>
            <value>
                <fullName>Word of Mouth on Order Cancellation</fullName>
            </value>
            <value>
                <fullName>Know more about products</fullName>
            </value>
            <value>
                <fullName>Product Suitability</fullName>
            </value>
            <value>
                <fullName>Product Quantity or Ingredients or Description</fullName>
            </value>
            <value>
                <fullName>Stock / Restock</fullName>
            </value>
            <value>
                <fullName>Product life /Expiry/Authencity /Others</fullName>
            </value>
            <value>
                <fullName>Collaboration Request/Influencer queries</fullName>
            </value>
            <value>
                <fullName>Collaboration service issues</fullName>
            </value>
            <value>
                <fullName>Collaboration Request</fullName>
            </value>
            <value>
                <fullName>Content Issues - Cx</fullName>
            </value>
            <value>
                <fullName>Content Issues - Partners</fullName>
            </value>
            <value>
                <fullName>Order Status</fullName>
            </value>
            <value>
                <fullName>Gift Before Shipping</fullName>
            </value>
            <value>
                <fullName>Gift After Shipping</fullName>
            </value>
            <value>
                <fullName>Cancellation Before Shipping</fullName>
            </value>
            <value>
                <fullName>Cancellation After Shipping</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/showAllRelatedCasesController.cls
public class showAllRelatedCasesController {
    @AuraEnabled(cacheable = true)
    public static List<Case> getCaseList(String chatTranscripId){
        try{
            if(chatTranscripId != null && string.valueOf(chatTranscripId).startsWith('570')){
                List<LiveChatTranscript> caseList1 = [SELECT Id, CaseId FROM LiveChatTranscript WHERE Id=: chatTranscripId LIMIT 1];
                String caseId;
                if(!caseList1.isEmpty()){
                    caseId = caseList1[0].CaseId;
                }
                if(caseId != null){
                    Case caseRec = [SELECT Id, CaseNumber, OrderId__c, OrderId__r.AccountId, ContactId, AccountId FROM Case WHERE Id=: caseId LIMIT 1];
                    String orderId;
                    String accountId;
                    String caseContactId;
                    String caseAccountId;
                    if(caseRec.OrderId__c != null){
                        orderId = caseRec.OrderId__c;
                    }
                    if(caseRec.OrderId__r.AccountId != null){
                        accountId = caseRec.OrderId__r.AccountId;
                    }
                    if(caseRec.ContactId != null){
                        caseContactId = caseRec.ContactId;
                    }
                    if(caseRec.AccountId != null){
                        caseAccountId = caseRec.AccountId;
                    }
                List<Case> caseList =[SELECT Id, CaseNumber, OrderId__c, OrderId__r.AccountId, Status, Origin, Subject, Priority,Sub_Sub_Type__c, Sub_Type__c FROM Case WHERE (OrderId__c =: orderId OR AccountId =: accountId OR ContactId =: caseContactId OR AccountId =: caseAccountId) AND Status != 'Closed' ORDER BY CreatedDate DESC];
                return caseList;
                }
                return null;
            }else if(chatTranscripId != null && string.valueOf(chatTranscripId).startsWith('500')){
            Case caseRec = [SELECT Id, CaseNumber, OrderId__c, OrderId__r.AccountId, ContactId, AccountId FROM Case WHERE Id=: chatTranscripId LIMIT 1];
            String orderId;
            String accountId;
            String caseContactId;
            String caseAccountId;
            if(caseRec.OrderId__c != null){
                orderId = caseRec.OrderId__c;
            }else{
                orderId = '0';
            }
            if(caseRec.OrderId__r.AccountId != null){
                accountId = caseRec.OrderId__r.AccountId;
            }else{
                accountId = '0';
            }
            if(caseRec.ContactId != null){
                caseContactId = caseRec.ContactId;
            }else{
                caseContactId = '0';
            }
            if(caseRec.AccountId != null){
                caseAccountId = caseRec.AccountId;
            }else{
                caseAccountId = '0';
            }
            List<Case> caseList =[SELECT Id, CaseNumber, OrderId__c, OrderId__r.AccountId, Status, Origin, Subject, Priority,Sub_Sub_Type__c, Sub_Type__c FROM Case WHERE (OrderId__c =: orderId OR AccountId =: accountId OR ContactId =: caseContactId OR AccountId =: caseAccountId) AND Status != 'Closed' ORDER BY CreatedDate DESC];
                return caseList;
        }else{
                return null;
            }
        }catch(exception e){
            System.debug('Error Message==> ' + e.getMessage() + ' at line number ' + e.getLineNumber());
            return null;
        }
    }
}