force-app/main/default/objects/Case/fields/OrderId__c.field-meta.xml
<CustomField>
    <fullName>OrderId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Order.Name</field>
            <operation>notContain</operation>
            <value>-</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Sub_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Sub_Sub_Type__c</fullName>
    <label>Sub Sub Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sub_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Login issues/Login number error</fullName>
            </value>
            <value>
                <fullName>Invalid Email/Phone Number</fullName>
            </value>
            <value>
                <fullName>Invalid Coupon Code</fullName>
            </value>
            <value>
                <fullName>App Stuck or Hanged</fullName>
            </value>
            <value>
                <fullName>Error while adding in cart</fullName>
            </value>
            <value>
                <fullName>Product Description/Offer Issues</fullName>
            </value>
            <value>
                <fullName>Addition of More Payment options or COD</fullName>
            </value>
            <value>
                <fullName>Refund Issues</fullName>
            </value>
            <value>
                <fullName>Change in profile number</fullName>
            </value>
            <value>
                <fullName>Updation of new email id</fullName>
            </value>
            <value>
                <fullName>Change in mail id</fullName>
            </value>
            <value>
                <fullName>Process to add/update more addresses</fullName>
            </value>
            <value>
                <fullName>Guided on App</fullName>
            </value>
            <value>
                <fullName>Price mismatch</fullName>
            </value>
            <value>
                <fullName>Comparison with Competitor</fullName>
            </value>
            <value>
                <fullName>Ongoing Campaign/Sales updates</fullName>
            </value>
            <value>
                <fullName>Upcoming Campaign /Sales updates</fullName>
            </value>
            <value>
                <fullName>How to check product review</fullName>
            </value>
            <value>
                <fullName>Giveaway inquiry</fullName>
            </value>
            <value>
                <fullName>Use of Coupon codes</fullName>
            </value>
            <value>
                <fullName>Coupon/Freebie /Discount/Cashback Issuance</fullName>
            </value>
            <value>
                <fullName>Gift an Order</fullName>
            </value>
            <value>
                <fullName>Information Given</fullName>
            </value>
            <value>
                <fullName>Guided to explore personalization on app</fullName>
            </value>
            <value>
                <fullName>Collabration Request/Influencer queries</fullName>
            </value>
            <value>
                <fullName>Collabration service issues</fullName>
            </value>
            <value>
                <fullName>Collabration Request</fullName>
            </value>
            <value>
                <fullName>Content Issues - Cx</fullName>
            </value>
            <value>
                <fullName>Content Issues - Partners</fullName>
            </value>
            <value>
                <fullName>Order number confirmation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Sub_Type__c</fullName>
    <label>Sub Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Order Related</fullName>
            </value>
            <value>
                <fullName>App Related</fullName>
            </value>
            <value>
                <fullName>Refund Issues</fullName>
            </value>
            <value>
                <fullName>Mobile number change</fullName>
            </value>
            <value>
                <fullName>Update Email id</fullName>
            </value>
            <value>
                <fullName>Process to add or update more addresses</fullName>
            </value>
            <value>
                <fullName>Product Price</fullName>
            </value>
            <value>
                <fullName>Comparison with Competitor</fullName>
            </value>
            <value>
                <fullName>Offers and Promotions</fullName>
            </value>
            <value>
                <fullName>Gift / Pre-book</fullName>
            </value>
            <value>
                <fullName>Process to Purchase / Delivery Charges</fullName>
            </value>
            <value>
                <fullName>Expected Delivery TAT / Preferred Delivery window</fullName>
            </value>
            <value>
                <fullName>Previous order OOS Req for benefit/code</fullName>
            </value>
            <value>
                <fullName>Missed campaign Req. for Benefit/code</fullName>
            </value>
            <value>
                <fullName>Word of Mouth on Order Cancellation</fullName>
            </value>
            <value>
                <fullName>Know more about products</fullName>
            </value>
            <value>
                <fullName>Product Suitability</fullName>
            </value>
            <value>
                <fullName>Product Quantity or Ingredients or Description</fullName>
            </value>
            <value>
                <fullName>Stock / Restock</fullName>
            </value>
            <value>
                <fullName>Product life /Expiry/Authencity /Others</fullName>
            </value>
            <value>
                <fullName>Collaboration Request/Influencer queries</fullName>
            </value>
            <value>
                <fullName>Collaboration service issues</fullName>
            </value>
            <value>
                <fullName>Collaboration Request</fullName>
            </value>
            <value>
                <fullName>Content Issues - Cx</fullName>
            </value>
            <value>
                <fullName>Content Issues - Partners</fullName>
            </value>
            <value>
                <fullName>Order Status</fullName>
            </value>
            <value>
                <fullName>Gift Before Shipping</fullName>
            </value>
            <value>
                <fullName>Gift After Shipping</fullName>
            </value>
            <value>
                <fullName>Cancellation Before Shipping</fullName>
            </value>
            <value>
                <fullName>Cancellation After Shipping</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RecordTypeDependentPicklist__mdt/RecordTypeDependentPicklist__mdt.object-meta.xml
<CustomObject>
    <label>RecordTypeDependentPicklist</label>
    <pluralLabel>RecordTypeDependentPicklist</pluralLabel>
</CustomObject>

force-app/main/default/objects/RecordTypeDependentPicklist__mdt/fields/Sub_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Sub_Sub_Type__c</fullName>
    <label>Sub Sub Type</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/RecordTypeDependentPicklist__mdt/fields/Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Sub_Type__c</fullName>
    <label>Sub Type</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/ContactFormWithPhoneNoVfController.cls
public class ContactFormWithPhoneNoVfController {
    

    @RemoteAction
    public static Account searchCustomer(string formattedPhone){
        try{
            if(formattedPhone != null){
                Account customerRecord = [SELECT Id,Name,Phone_10_Digit__c, Alternate_Phone_No__c From Account WHERE Phone_10_Digit__c =: formattedPhone LIMIT 1];
                if(customerRecord != null)
                return customerRecord;
            }
            return null;
        }catch(Exception e){
            system.debug('Error :'+e.getMessage());
            return null;
        }
    }

    @RemoteAction
    public static Order searchOrder(string searchValue){
        try{
            if(searchValue != null){
                Order orderecord = [SELECT Id,Name,Status,Account.Name,Account.Phone_10_Digit__c,Account.Alternate_Phone_No__c From Order WHERE Name =: searchValue];
                if(orderecord != null){
                    return orderecord;
                }
            }
            return null;
        }catch(Exception e){
            return null;
        }
    }
    
    @RemoteAction
    public static List<RecordTypeDependentPicklist__mdt> getMetaData(){
        try{
            List<RecordTypeDependentPicklist__mdt> recordsOfMetaData = [select id,Type__c,Sub_Type__c,Sub_Sub_Type__c from RecordTypeDependentPicklist__mdt ];
            return recordsOfMetaData;
        }catch(Exception e){
            system.debug('Error :'+e.getMessage());
            return null;
        }
        
    }

    @RemoteAction
    public static String saveCaseWithCustomerDetails(String recordTypeName, Account accRec, Case caserecord){
        try{
            update accRec;
            Id recordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get(recordTypeName).getRecordTypeId();
            caserecord.RecordTypeId = recordTypeId;
            caserecord.AccountId = accRec.Id;
            insert caserecord;
            return 'Success';
        }catch(Exception e){
            return e.getMessage();
        }
    }

    @RemoteAction
    public static String saveOrderDetails(String recordTypeName, String orderId, Account accRec, case caserecord){
        try{
            update accRec;
            Id recordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get(recordTypeName).getRecordTypeId();
            caserecord.RecordTypeId = recordTypeId;
            caserecord.AccountId = accRec.Id;
            caserecord.OrderId__c = orderId;
            insert caserecord;
            return 'Success';
        }catch(Exception e){
            return e.getMessage();
        }
    }
    
    
    
    
    
    
    
    // public Lead ledRec {get;set;}
    // public String leadRecordString{get;set;}
    // public Contact conRec{get;set;}
    // public String contactRecordString{get;set;}
    
    // public Case cseRec{get;set;}
    // public String CaseRecordString{get;set;}
    // public Order ordRec{get;set;}
    // public String OrderRecordString{get;set;}
    // public Account accRec{get;set;}
    // public String AccountRecordString{get;set;}
    
    // Public ContactFormWithPhoneNoVfController() {
    //     try{
    //         String phoneNumber = Apexpages.currentPage().getParameters().get('id'); 
    //         conRec = [SELECT Id,Name,Account.Name,Email,Phone FROM Contact Where phone =: phoneNumber  LIMIT 1];
    //         System.debug('conRec ::'+conRec);
    //         if(conRec !=null){
    //             contactRecordString=JSON.serialize(conRec);
    //         }else{
    //             contactRecordString = 'Not Found';
    //         }
            
    //     }catch(Exception e){
    //         System.debug('Error ::'+e.getMessage() + ' Error Line ::'+e.getLineNumber());
    //     }
    // }
    
    // @RemoteAction
    // public Static List<String> getPickListValuesMethod(String ObjectApi_name, String Field_Name){
    //     try{
    //         List<String> lstPickvals                        = new List<String>();
    //         Schema.SObjectType targetType                   = Schema.getGlobalDescribe().get(ObjectApi_name);
    //         Sobject Object_name                             = targetType.newSObject();
    //         Schema.sObjectType sobject_type                 = Object_name.getSObjectType(); 
    //         Schema.DescribeSObjectResult sobject_describe   = sobject_type.getDescribe();
    //         Map<String, Schema.SObjectField> field_map      = sobject_describe.fields.getMap();
    //         List<Schema.PicklistEntry> pick_list_values     = field_map.get(Field_Name).getDescribe().getPickListValues();
            
    //         for (Schema.PicklistEntry a : pick_list_values) {
    //             lstPickvals.add(String.ValueOf(a.getLabel()).trim());  
    //         }
    //         System.debug('lstPickvals>>>> ::'+lstPickvals);
    //         return lstPickvals;
    //     }Catch(Exception e){
    //         System.debug('The Error ::'+e.getMessage() +' AND Error Line No :'+e.getLineNumber());
    //     }
    //     return null;
    // }
    
    // @RemoteAction
    // public Static lead updateLeadDetails(String leadId, String firstname,String lastname,String company,string state,String city,String street){
    //     //    System.debug('leadId ::'+leadId + ' && led Record ::'+led);
    //     try{
    //         Lead led = new Lead();
    //         led.Id = leadId;
    //         led.FirstName = firstname;
    //         led.LastName =lastname;
    //         led.Company = company;
    //         led.State = state;
    //         led.City = city;
    //         led.Street = street;
    //         update led;
    //         //   System.debug('Updated Lead ID::'+led.Id + ' && City Address:::'+led.Address);
    //         // System.debug('City Address:::'+led.Address);
    //         return led; 
    //     }catch(Exception e){
    //         System.debug('Error ::'+e.getMessage() + ' Error Line ::'+e.getLineNumber()); 
    //     }
    //     return null;
    // }
    
    // @RemoteAction
    // public Static lead updateLeadDate(String leadId, integer day, integer month, integer year ){
    //     lead led = new lead();
    //     led.Id = leadId;
    //     if(day==0 && month==0 && year==0){
            
    //     }else{
    //         // led.Followup_Date__c = Date.newInstance(year, month, day);
            
    //     }
    //     // led.Followup_Date__c = leddate;
    //     update led;
    //     return led;
    // }
    
    
}