force-app/main/default/objects/Case/fields/Sub_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Sub_Sub_Type__c</fullName>
    <label>Sub Sub Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sub_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Login issues/Login number error</fullName>
            </value>
            <value>
                <fullName>Invalid Email/Phone Number</fullName>
            </value>
            <value>
                <fullName>Invalid Coupon Code</fullName>
            </value>
            <value>
                <fullName>App Stuck or Hanged</fullName>
            </value>
            <value>
                <fullName>Error while adding in cart</fullName>
            </value>
            <value>
                <fullName>Product Description/Offer Issues</fullName>
            </value>
            <value>
                <fullName>Addition of More Payment options or COD</fullName>
            </value>
            <value>
                <fullName>Refund Issues</fullName>
            </value>
            <value>
                <fullName>Change in profile number</fullName>
            </value>
            <value>
                <fullName>Updation of new email id</fullName>
            </value>
            <value>
                <fullName>Change in mail id</fullName>
            </value>
            <value>
                <fullName>Process to add/update more addresses</fullName>
            </value>
            <value>
                <fullName>Guided on App</fullName>
            </value>
            <value>
                <fullName>Price mismatch</fullName>
            </value>
            <value>
                <fullName>Comparison with Competitor</fullName>
            </value>
            <value>
                <fullName>Ongoing Campaign/Sales updates</fullName>
            </value>
            <value>
                <fullName>Upcoming Campaign /Sales updates</fullName>
            </value>
            <value>
                <fullName>How to check product review</fullName>
            </value>
            <value>
                <fullName>Giveaway inquiry</fullName>
            </value>
            <value>
                <fullName>Use of Coupon codes</fullName>
            </value>
            <value>
                <fullName>Coupon/Freebie /Discount/Cashback Issuance</fullName>
            </value>
            <value>
                <fullName>Gift an Order</fullName>
            </value>
            <value>
                <fullName>Information Given</fullName>
            </value>
            <value>
                <fullName>Guided to explore personalization on app</fullName>
            </value>
            <value>
                <fullName>Collabration Request/Influencer queries</fullName>
            </value>
            <value>
                <fullName>Collabration service issues</fullName>
            </value>
            <value>
                <fullName>Collabration Request</fullName>
            </value>
            <value>
                <fullName>Content Issues - Cx</fullName>
            </value>
            <value>
                <fullName>Content Issues - Partners</fullName>
            </value>
            <value>
                <fullName>Order number confirmation</fullName>
            </value>
            <value>
                <fullName>Full</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Sub_Type__c</fullName>
    <label>Sub Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Order Related</fullName>
            </value>
            <value>
                <fullName>App Related</fullName>
            </value>
            <value>
                <fullName>Refund Issues</fullName>
            </value>
            <value>
                <fullName>Mobile number change</fullName>
            </value>
            <value>
                <fullName>Update Email id</fullName>
            </value>
            <value>
                <fullName>Process to add or update more addresses</fullName>
            </value>
            <value>
                <fullName>Product Price</fullName>
            </value>
            <value>
                <fullName>Comparison with Competitor</fullName>
            </value>
            <value>
                <fullName>Offers and Promotions</fullName>
            </value>
            <value>
                <fullName>Gift / Pre-book</fullName>
            </value>
            <value>
                <fullName>Process to Purchase / Delivery Charges</fullName>
            </value>
            <value>
                <fullName>Expected Delivery TAT / Preferred Delivery window</fullName>
            </value>
            <value>
                <fullName>Previous order OOS Req for benefit/code</fullName>
            </value>
            <value>
                <fullName>Missed campaign Req. for Benefit/code</fullName>
            </value>
            <value>
                <fullName>Word of Mouth on Order Cancellation</fullName>
            </value>
            <value>
                <fullName>Know more about products</fullName>
            </value>
            <value>
                <fullName>Product Suitability</fullName>
            </value>
            <value>
                <fullName>Product Quantity or Ingredients or Description</fullName>
            </value>
            <value>
                <fullName>Stock / Restock</fullName>
            </value>
            <value>
                <fullName>Product life /Expiry/Authencity /Others</fullName>
            </value>
            <value>
                <fullName>Collaboration Request/Influencer queries</fullName>
            </value>
            <value>
                <fullName>Collaboration service issues</fullName>
            </value>
            <value>
                <fullName>Collaboration Request</fullName>
            </value>
            <value>
                <fullName>Content Issues - Cx</fullName>
            </value>
            <value>
                <fullName>Content Issues - Partners</fullName>
            </value>
            <value>
                <fullName>Order Status</fullName>
            </value>
            <value>
                <fullName>Gift Before Shipping</fullName>
            </value>
            <value>
                <fullName>Gift After Shipping</fullName>
            </value>
            <value>
                <fullName>Cancellation Before Shipping</fullName>
            </value>
            <value>
                <fullName>Cancellation After Shipping</fullName>
            </value>
            <value>
                <fullName>Full</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/taskHelperControllerTest.cls
@isTest(seeAllData= true)
private class taskHelperControllerTest {
    
    @isTest
    static void testFetchDependentPicklist() {
        Test.startTest();
        Map<String, List<String>> result = taskHelperController.fetchDependentPicklist();
        Test.stopTest();
        
    }
    
    @isTest
    static void testDependentFields() {
        Test.startTest();
        Map<String, List<String>> result = taskHelperController.dependentFields();
        Test.stopTest();
        
    }
    
    @isTest
    static void testGetOrderItems() {
        
        Account testAccount = new Account(Name = 'Test Account', Phone = '12345678');
        insert testAccount;
        
        Product2 objProduct = new Product2();
        objProduct.Name = 'Tesrtt';
        objProduct.Description = 'Tesrt';
        Insert objProduct;
        
        PriceBook2 pb2Standard = [Select Id from Pricebook2 where isStandard=true limit 1];
        
        PricebookEntry objPBEntry = new PricebookEntry();
        objPBEntry.Pricebook2Id =pb2Standard.id;
        objPBEntry.Product2Id = objProduct.id;
        objPBEntry.UnitPrice = 100;  
        objPBEntry.IsActive = true;
        Insert objPBEntry;
        
        /*Case testCase = new Case(Sub_Type__c = 'Full', Sub_Sub_Type__c = 'Full', Status = 'Open');
insert testCase;*/
        
        Order testOrder = new Order(Name='234452',AccountId = testAccount.Id, Status = 'Draft',EffectiveDate=system.today(),Pricebook2Id = pb2Standard.Id);
        insert testOrder;
        
        Order testOrder1 = new Order(Name='234452',AccountId = testAccount.Id, Status = 'Draft',EffectiveDate=system.today(),Pricebook2Id = pb2Standard.Id,ParentOrder__c = testOrder.Id);
        insert testOrder1;
        
        Test.startTest();
        List<OrderItem> result = taskHelperController.getOrderItems(testOrder.Id);
        Test.stopTest();
        
    }
    
    @isTest
    static void testCreateCaseFromCase() {
        
        Account testAccount = new Account(Name = 'Test Account', Phone='12345678');
        insert testAccount;
        
        Product2 objProduct = new Product2();
        objProduct.Name = 'Tesrtt';
        objProduct.Description = 'Tesrt';
        Insert objProduct;
        
        PriceBook2 pb2Standard = [Select Id from Pricebook2 where isStandard=true limit 1];
        
        PricebookEntry objPBEntry = new PricebookEntry();
        objPBEntry.Pricebook2Id =pb2Standard.id;
        objPBEntry.Product2Id = objProduct.id;
        objPBEntry.UnitPrice = 100;  
        objPBEntry.IsActive = true;
        Insert objPBEntry;
        
        Case testCase = new Case(
            Subject = 'Test Case',
            AccountId = testAccount.Id,
            Status = 'New'
        );
        insert testCase;
        
        Order testOrder = new Order(Name='234452',AccountId = testAccount.Id, Status = 'Draft',EffectiveDate=system.today(),Pricebook2Id = pb2Standard.Id);
        insert testOrder;
        
        Order testOrder1 = new Order(Name='234452',AccountId = testAccount.Id, Status = 'Draft',EffectiveDate=system.today(),Pricebook2Id = pb2Standard.Id,ParentOrder__c = testOrder.Id);
        insert testOrder1;
        
        Task testTasks = new Task(WhatId = testCase.Id);
        insert testTasks;
        
        Test.startTest();
        taskHelperController.getCaseRecords();
        Case result = taskHelperController.createCaseFromCase('Subject', '234126', testTasks.Id, testOrder.Id);
        Test.stopTest();        
    }
}