force-app/main/default/objects/Follow_Up_Request__c/Follow_Up_Request__c.object-meta.xml
<CustomObject>
    <label>Follow Up Request</label>
    <nameField>
        <displayFormat>FUP-{0000}</displayFormat>
        <label>Follow Up Requests Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Follow Up Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Follow_Up_Request__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Follow Up Requests</relationshipLabel>
    <relationshipName>Follow_Up_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Follow_Up_Request__c/fields/Follow_Up_Status__c.field-meta.xml
<CustomField>
    <fullName>Follow_Up_Status__c</fullName>
    <label>Follow Up Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Responded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/followUpTriggerHelperTest.cls
@isTest
public class followUpTriggerHelperTest {
	@isTest
    static void testClass(){
        //followUpTriggerHelper.dumMethod();
        List<Follow_Up_Request__c> listofFol = new List<Follow_Up_Request__c>();
        case testcase = new case();
        testcase.Status = 'New';
        testcase.Subject = 'Test Case';
        insert testcase;
        
        Follow_Up_Request__c fol = new Follow_Up_Request__c();
        fol.Follow_Up_Status__c  = 'Open';
        fol.Case__c = testcase.Id;
        listofFol.add(fol);
        insert listofFol;
        
        List<Follow_Up_Request__c> listofFol1 = new List<Follow_Up_Request__c>();
        case testcase1 = new case();
        testcase.Status = 'New';
        testcase.Subject = 'Test Case';
        insert testcase1;
        
        Follow_Up_Request__c fol1 = new Follow_Up_Request__c();
        fol.Follow_Up_Status__c  = 'Responded';
        fol.Case__c = testcase1.Id;
        listofFol1.add(fol1);
        insert listofFol1;
        
        followUpTriggerHelper.updateCaseOnFollowUpCreation(listofFol);
        followUpTriggerHelper.updateCaseOnFollowUpUpdation(listofFol);
        followUpTriggerHelper.OnInsertOrUpdateLastResponseOnCase(listofFol);
         followUpTriggerHelper.OnInsertOrUpdateLastResponseOnCase(listofFol1);

        
    }
}