force-app/main/default/objects/Affected_SKU__c/Affected_SKU__c.object-meta.xml
<CustomObject>
    <label>Affected SKU</label>
    <nameField>
        <label>Affected SKU Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Affected SKUs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Affected_SKU__c/fields/Brand_Name__c.field-meta.xml
<CustomField>
    <fullName>Brand_Name__c</fullName>
    <label>Brand Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Affected_SKU__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Affected SKUs</relationshipLabel>
    <relationshipName>Affected_SKUs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Affected_SKU__c/fields/Order_Item__c.field-meta.xml
<CustomField>
    <fullName>Order_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Item</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Affected SKUs</relationshipLabel>
    <relationshipName>Affected_SKUs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Approval_Remarks__c.field-meta.xml
<CustomField>
    <fullName>Approval_Remarks__c</fullName>
    <label>Approval Remarks</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/Brand_Name__c.field-meta.xml
<CustomField>
    <fullName>Brand_Name__c</fullName>
    <label>Brand Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Communication_Mode__c.field-meta.xml
<CustomField>
    <fullName>Communication_Mode__c</fullName>
    <label>Communication Mode</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Call</fullName>
            </value>
            <value>
                <fullName>Chat</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Social - IG</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/CS_Team_Member__c.field-meta.xml
<CustomField>
    <fullName>CS_Team_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CS Team Member</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Cases3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/CSE_Remarks__c.field-meta.xml
<CustomField>
    <fullName>CSE_Remarks__c</fullName>
    <label>CSE Remarks</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/Describe_Information_Needed__c.field-meta.xml
<CustomField>
    <fullName>Describe_Information_Needed__c</fullName>
    <label>Describe Information Needed</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/Marketing_Team__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Marketing Team Member</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Cases1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/OOS_Quantity__c.field-meta.xml
<CustomField>
    <fullName>OOS_Quantity__c</fullName>
    <label>OOS Quantity</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/OrderId__c.field-meta.xml
<CustomField>
    <fullName>OrderId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Order.Name</field>
            <operation>notContain</operation>
            <value>-</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Refer_Back_Reason__c.field-meta.xml
<CustomField>
    <fullName>Refer_Back_Reason__c</fullName>
    <label>Refer Back Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Resolved</fullName>
            </value>
            <value>
                <fullName>Need More Info</fullName>
            </value>
            <value>
                <fullName>Send Update</fullName>
            </value>
            <value>
                <fullName>Wrongly Sent</fullName>
            </value>
            <value>
                <fullName>Address Changed</fullName>
                <isActive>false</isActive>
                <label>Address Changed</label>
            </value>
            <value>
                <fullName>Cancellation Processed</fullName>
                <isActive>false</isActive>
                <label>Cancellation Processed</label>
            </value>
            <value>
                <fullName>Cancellation Rejected</fullName>
                <isActive>false</isActive>
                <label>Cancellation Rejected</label>
            </value>
            <value>
                <fullName>Refund Processed</fullName>
                <isActive>false</isActive>
                <label>Refund Processed</label>
            </value>
            <value>
                <fullName>Refund Rejected</fullName>
                <isActive>false</isActive>
                <label>Refund Rejected</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/SKU_Details__c.field-meta.xml
<CustomField>
    <fullName>SKU_Details__c</fullName>
    <label>SKU Details</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Sub_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Sub_Sub_Type__c</fullName>
    <label>Sub Sub Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sub_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Login issues/Login number error</fullName>
            </value>
            <value>
                <fullName>Invalid Email/Phone Number</fullName>
            </value>
            <value>
                <fullName>Invalid Coupon Code</fullName>
            </value>
            <value>
                <fullName>App Stuck or Hanged</fullName>
            </value>
            <value>
                <fullName>Error while adding in cart</fullName>
            </value>
            <value>
                <fullName>Product Description/Offer Issues</fullName>
            </value>
            <value>
                <fullName>Addition of More Payment options or COD</fullName>
            </value>
            <value>
                <fullName>Refund Issues</fullName>
            </value>
            <value>
                <fullName>Change in profile number</fullName>
            </value>
            <value>
                <fullName>Updation of new email id</fullName>
            </value>
            <value>
                <fullName>Change in mail id</fullName>
            </value>
            <value>
                <fullName>Process to add/update more addresses</fullName>
            </value>
            <value>
                <fullName>Guided on App</fullName>
            </value>
            <value>
                <fullName>Price mismatch</fullName>
            </value>
            <value>
                <fullName>Comparison with Competitor</fullName>
            </value>
            <value>
                <fullName>Ongoing Campaign/Sales updates</fullName>
            </value>
            <value>
                <fullName>Upcoming Campaign /Sales updates</fullName>
            </value>
            <value>
                <fullName>How to check product review</fullName>
            </value>
            <value>
                <fullName>Giveaway inquiry</fullName>
            </value>
            <value>
                <fullName>Use of Coupon codes</fullName>
            </value>
            <value>
                <fullName>Coupon/Freebie /Discount/Cashback Issuance</fullName>
            </value>
            <value>
                <fullName>Gift an Order</fullName>
            </value>
            <value>
                <fullName>Information Given</fullName>
            </value>
            <value>
                <fullName>Guided to explore personalization on app</fullName>
            </value>
            <value>
                <fullName>Collabration Request/Influencer queries</fullName>
            </value>
            <value>
                <fullName>Collabration service issues</fullName>
            </value>
            <value>
                <fullName>Collabration Request</fullName>
            </value>
            <value>
                <fullName>Content Issues - Cx</fullName>
            </value>
            <value>
                <fullName>Content Issues - Partners</fullName>
            </value>
            <value>
                <fullName>Order number confirmation</fullName>
            </value>
            <value>
                <fullName>Order Confirmation /Status Issues</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Sub_Type__c</fullName>
    <label>Sub Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Order Related</fullName>
            </value>
            <value>
                <fullName>App Related</fullName>
            </value>
            <value>
                <fullName>Refund Issues</fullName>
            </value>
            <value>
                <fullName>Mobile number change</fullName>
            </value>
            <value>
                <fullName>Update Email id</fullName>
            </value>
            <value>
                <fullName>Process to add or update more addresses</fullName>
            </value>
            <value>
                <fullName>Product Price</fullName>
            </value>
            <value>
                <fullName>Comparison with Competitor</fullName>
            </value>
            <value>
                <fullName>Offers and Promotions</fullName>
            </value>
            <value>
                <fullName>Gift / Pre-book</fullName>
            </value>
            <value>
                <fullName>Process to Purchase / Delivery Charges</fullName>
            </value>
            <value>
                <fullName>Expected Delivery TAT / Preferred Delivery window</fullName>
            </value>
            <value>
                <fullName>Previous order OOS Req for benefit/code</fullName>
            </value>
            <value>
                <fullName>Missed campaign Req. for Benefit/code</fullName>
            </value>
            <value>
                <fullName>Word of Mouth on Order Cancellation</fullName>
            </value>
            <value>
                <fullName>Know more about products</fullName>
            </value>
            <value>
                <fullName>Product Suitability</fullName>
            </value>
            <value>
                <fullName>Product Quantity or Ingredients or Description</fullName>
            </value>
            <value>
                <fullName>Stock / Restock</fullName>
            </value>
            <value>
                <fullName>Product life /Expiry/Authencity /Others</fullName>
            </value>
            <value>
                <fullName>Collaboration Request/Influencer queries</fullName>
            </value>
            <value>
                <fullName>Collaboration service issues</fullName>
            </value>
            <value>
                <fullName>Collaboration Request</fullName>
            </value>
            <value>
                <fullName>Content Issues - Cx</fullName>
            </value>
            <value>
                <fullName>Content Issues - Partners</fullName>
            </value>
            <value>
                <fullName>Order Status</fullName>
            </value>
            <value>
                <fullName>Gift Before Shipping</fullName>
            </value>
            <value>
                <fullName>Gift After Shipping</fullName>
            </value>
            <value>
                <fullName>Cancellation Before Shipping</fullName>
            </value>
            <value>
                <fullName>Cancellation After Shipping</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/UTR_Number__c.field-meta.xml
<CustomField>
    <fullName>UTR_Number__c</fullName>
    <label>UTR Number</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Warehouse_Team_Member__c.field-meta.xml
<CustomField>
    <fullName>Warehouse_Team_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Warehouse Team Member</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Cases2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/caseTriggerHelperTest.cls
@isTest(seeAllData = true)
public class caseTriggerHelperTest {
    @isTest
    static void testResetTypeAndSubtypeOnRecordTypeChange() {
        Profile pro = [SELECT Id,Name FROM Profile WHERE Name='WareHouse Team' LIMIT 1]; 
        User userInstant = new User(Alias = 'standt', Email='sossfdc@cirrologix.com', 
                                    EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
                                    IsActive=true, Division='Rainmakers',
                                    LocaleSidKey='en_US', ProfileId = pro.Id,
                                    TimeZoneSidKey='America/Los_Angeles', UserName='standardVarsha1234565432@testorg.com');
        insert userInstant;
        
        Account testAccount = new Account(Name = 'Test Account', Phone ='123456789');
        insert testAccount;
        
       Id RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Social Media').getRecordTypeId();
        system.debug('RecordTypeId ::'+RecordTypeId);
        
        Contact con = new Contact();
        con.accountId = testAccount.Id;
        con.Email = 'new@contact.com';
        con.FirstName = 'Test';
        con.LastName = 'contact';
        Insert Con;
        
        Product2 objProduct = new Product2(Name = 'TestProduct', Description = 'Test Description');
        insert objProduct;
        
        PriceBook2 pb2Standard = [SELECT Id FROM Pricebook2 WHERE IsStandard = true LIMIT 1];
        Id standardPriceBookId = pb2Standard.Id;
        
        PricebookEntry objPBEntry = new PricebookEntry(Pricebook2Id = standardPriceBookId, Product2Id = objProduct.Id, UnitPrice = 100, IsActive = true);
        insert objPBEntry;
        
        Order testOrder = new Order(Name = 'TestOrder001', AccountId = testAccount.Id, Status = 'Draft', EffectiveDate = System.today(), Pricebook2Id = standardPriceBookId);
        insert testOrder;
        
        Order subOrder = new Order(Name = 'TestOrder001-SubOrder001', ParentOrder__c = testOrder.Id, AccountId = testAccount.Id, Status = 'Draft', EffectiveDate = Date.today(), Pricebook2Id = standardPriceBookId);
        insert subOrder;
        
        OrderItem orderItem = new OrderItem(OrderId = subOrder.Id, Quantity = 1, UnitPrice = 100.00, SKU__c = 'SKU001', PricebookEntryId = objPBEntry.Id,Is_Already_Utilized__c = False,Refund_Price__c = 123);
        insert orderItem;     
        OrderItem orderItem1 = new OrderItem(OrderId = subOrder.Id, Quantity = 1, UnitPrice = 100.00, SKU__c = 'SKU001', PricebookEntryId = objPBEntry.Id,Is_Already_Utilized__c = False,Refund_Price__c = 123);
        insert orderItem1;     
        
        Case cse = new Case(Origin = 'Bulk Upload', Status = 'New',RecordTypeId=RecordTypeId, AccountId = testAccount.Id, OrderId__c = testOrder.Id, ContactId = con.Id,
                            Subject = 'Testing', SKU_Details__c = 'testingqwerty', OwnerId = userInstant.Id);
        insert cse;
       Id recTypeId= Schema.SObjectType.Case.getRecordTypeInfosByName().get('Inbound Case').getRecordTypeId();
        system.debug('recTypeId ::'+recTypeId);
        Case cs = new Case();
        cs.id = cse.Id;
        cs.RecordTypeId = recTypeId;
        update cs;
        /*
        Map<Id, Case> oldMap = new Map<Id, Case>{cse.Id => cse};
        
        Test.startTest();
       		caseTriggerHelper.resetTypeAndSubtypeOnRecordTypeChange(new List<Case>{cse}, oldMap);
        Test.stopTest();
*/
        
    }

    @isTest
    static void testCreatedAffectedSKUs() {
        Account acc = new Account(Name = 'Test Account', phone = '213456789');
        insert acc;
        
        Product2 objProduct = new Product2();
        objProduct.Name = 'Test';
        objProduct.Description = 'Test';
        Insert objProduct;
        
        Pricebook2 pb = new Pricebook2(Name = 'Standard Price Book 2009', Description = 'Price Book 2009 Products', IsActive = true );
        insert pb;
        Product2 prod = new Product2(Name = 'SLA: Bronze', IsActive = true);
        insert prod;
        
        // First insert a price for the standard price book
        Pricebook2 standardPB = [select id from Pricebook2 where isStandard=true];
        PricebookEntry standardPBE = new PricebookEntry(Pricebook2Id = standardPB.Id, Product2Id = prod.Id, UnitPrice = 1000, IsActive = true);
        insert standardPBE;
        PricebookEntry pbe = new PricebookEntry(Pricebook2Id = pb.Id, Product2Id = prod.Id, UnitPrice = 1000, IsActive = true);
        insert pbe;
        
        Order ord = new order();
        ord.AccountId = acc.Id;
        ord.EffectiveDate = system.today();
        ord.Status = 'Draft';
        ord.Pricebook2Id = pb.id;
        ord.UTR_Number__c = '123456';
        Insert ord;        
        
        List<Case> cs = new List<Case>();
        Case cse = new Case(Origin = 'Bulk Upload', Status = 'New', AccountId = acc.Id, OrderId__c = ord.Id, SKU_Details__c = 'TestSKU;TestSKU2', OOS_Quantity__c = '1;2');
        cs.add(cse);
        insert cs;
         
        List<OrderItem> orItmList = new List<OrderItem>();        
        OrderItem ordItm = new OrderItem();
        ordItm.OrderId = ord.Id;
        ordItm.UnitPrice = 200;
        ordItm.PricebookEntryId = pbe.Id;
        ordItm.Quantity = 1;
        ordItm.SKU__c = 'TestSKU';
        orItmList.add(ordItm);
        Insert orItmList;
        
        Affected_SKU__c afs = new Affected_SKU__c();
        afs.Case__c = cse.Id;
        afs.Brand_Name__c = 'Test';
        afs.Order_Item__c = ordItm.Id;
        insert afs;
        
        Test.startTest();
        caseTriggerHelper.createdAffectedSKUs(cs);
        Test.stopTest();
    }

    @isTest
    static void testUpdateUserFieldsOnReassignment() {
        Profile pro = [SELECT Id,Name FROM Profile WHERE Name='Customer Service Executive' LIMIT 1]; 
        User userInstant = new User(Alias = 'standt', Email='sossfdc@cirrologix.com', 
                                    EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
                                    IsActive=true, Division='Rainmakers',
                                    LocaleSidKey='en_US', ProfileId = pro.Id,
                                    TimeZoneSidKey='America/Los_Angeles', UserName='standardVarsha1234565432@testorg.com');
        insert userInstant;
        
        Account acc = new Account(Name = 'Testing', Phone = '098765432123456');
        insert acc;
        
        Contact con = new Contact(AccountId = acc.Id, Email = 'new@contact.com', FirstName = 'Test', LastName = 'contact');
        insert con;
        
        Case cse = new Case(Origin = 'Bulk Upload', Status = 'New', AccountId = acc.Id, ContactId = con.Id, OwnerId = userInstant.Id);
        insert cse;
        
        Case cseOld = cse.clone(false, true);
        cse.OwnerId = userInstant.Id;
        update cse;
        
        Map<Id, Case> oldMap = new Map<Id, Case>{cseOld.Id => cseOld};
        
        Test.startTest();
        caseTriggerHelper.updateUserFieldsOnReassignment(new List<Case>{cse}, oldMap);
        Test.stopTest();
        
        Case updatedCase = [SELECT CS_Team_Member__c FROM Case WHERE Id = :cse.Id];
        System.assertEquals(userInstant.Id, updatedCase.CS_Team_Member__c);
    }

    @isTest
    static void testSendEmailTemplateWithTemplate() {
        Profile pro = [SELECT Id,Name FROM Profile WHERE Name='Customer Service Executive' LIMIT 1]; 
        User userInstant = new User(Alias = 'standt', Email='sossfdc@cirrologix.com', 
                                    EmailEncodingKey='UTF-8', LastName='Testing',FirstName='Banoj', LanguageLocaleKey='en_US',
                                    IsActive=true, Division='Rainmakers',
                                    LocaleSidKey='en_US', ProfileId = pro.Id,
                                    TimeZoneSidKey='America/Los_Angeles', UserName='standardVarsha1234565432@testorg.com');
        insert userInstant;
        
        Account acc = new Account(Name = 'Testing', Phone = '098765432123456');
        insert acc;
        
        Contact con = new Contact(AccountId = acc.Id, Email = 'new@contact.com', FirstName = 'Test', LastName = 'contact');
        insert con;
        
        Case cse = new Case(Origin = 'Bulk Upload', Status = 'New', AccountId = acc.Id, ContactId = con.Id, 
                            OwnerId = userInstant.Id,Marketing_Team__c=userInstant.Id, 
                            Warehouse_Team_Member__c=userInstant.Id,Sub_Type__c='Order Related',
                            Subject='test subject',Sub_Sub_Type__c='Order Confirmation /Status Issues',CSE_Remarks__c='test remarks',
                           Refer_Back_Reason__c='Resolved',Approval_Remarks__c='test approval',Rejection_Reason__c='test reason',
                           Describe_Information_Needed__c='test description');
        insert cse;
        Map<Id, User> userMap = new Map<Id, User>{userInstant.Id => userInstant};
        
        Test.startTest();
        caseTriggerHelper.SendEmailTemplateWithTemplate(new List<Case>{cse}, userMap);
        Test.stopTest();
        
        // Add assertions as needed based on the email sending logic.
    }

    @isTest
    static void testSendingCustomNotification() {
        Profile pro = [SELECT Id,Name FROM Profile WHERE Name='Customer Service Executive' LIMIT 1]; 
        User userInstant = new User(Alias = 'standt', Email='sossfdc@cirrologix.com', 
                                    EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
                                    IsActive=true, Division='Rainmakers',
                                    LocaleSidKey='en_US', ProfileId = pro.Id,
                                    TimeZoneSidKey='America/Los_Angeles', UserName='standardVarsha1234565432@testorg.com');
        insert userInstant;
        
        Account acc = new Account(Name = 'Testing', Phone = '098765432123456');
        insert acc;
        
        Contact con = new Contact(AccountId = acc.Id, Email = 'new@contact.com', FirstName = 'Test', LastName = 'contact');
        insert con;
        
        Case cse = new Case(Origin = 'Bulk Upload', Status = 'New', AccountId = acc.Id, ContactId = con.Id, OwnerId = userInstant.Id);
        insert cse;
        
        Test.startTest();
        caseTriggerHelper.sendingCustomNotification(userInstant.Id, cse.Id, 'Case Assigned', 'A case has been assigned to you.');
        Test.stopTest();
        
        // Add assertions as needed based on the notification logic.*/
    }

    @isTest
    static void testModifyEmailCases() {
        Profile pro = [SELECT Id,Name FROM Profile WHERE Name='Customer Service Executive' LIMIT 1]; 
        User userInstant = new User(Alias = 'standt', Email='sossfdc@cirrologix.com', 
                                    EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
                                    IsActive=true, Division='Rainmakers',
                                    LocaleSidKey='en_US', ProfileId = pro.Id,
                                    TimeZoneSidKey='America/Los_Angeles', UserName='standardVarsha1234565432@testorg.com');
        insert userInstant;
        
        Account acc = new Account(Name = 'Testing', Phone = '098765432123456');
        insert acc;
        
        Contact con = new Contact(AccountId = acc.Id, Email = 'new@contact.com', FirstName = 'Test', LastName = 'contact');
        insert con;
        
        Case cse = new Case(Origin = 'Inbound Email', Status = 'New', AccountId = acc.Id, ContactId = con.Id, OwnerId = userInstant.Id, SuppliedEmail = 'new@contact.com');
        insert cse;
        
        Test.startTest();
        caseTriggerHelper.modifyEmailCases(new List<Case>{cse});
        caseTriggerHelper.dumMethod();
        Test.stopTest();
        
        Case updatedCase = [SELECT Communication_Mode__c FROM Case WHERE Id = :cse.Id];
      
    } 
       
}