force-app/main/default/objects/Affected_SKU__c/Affected_SKU__c.object-meta.xml
<CustomObject>
    <label>Affected SKU</label>
    <nameField>
        <label>Affected SKU Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Affected SKUs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Affected_SKU__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Affected SKUs</relationshipLabel>
    <relationshipName>Affected_SKUs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Approval_Remarks__c.field-meta.xml
<CustomField>
    <fullName>Approval_Remarks__c</fullName>
    <label>Approval Remarks</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/Describe_Information_Needed__c.field-meta.xml
<CustomField>
    <fullName>Describe_Information_Needed__c</fullName>
    <label>Describe Information Needed</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/Inital_Commented_Date__c.field-meta.xml
<CustomField>
    <fullName>Inital_Commented_Date__c</fullName>
    <label>Inital Commented Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/OrderId__c.field-meta.xml
<CustomField>
    <fullName>OrderId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Order.Name</field>
            <operation>notContain</operation>
            <value>-</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Reason_For_Dealy__c.field-meta.xml
<CustomField>
    <fullName>Reason_For_Dealy__c</fullName>
    <label>Reason For Dealy</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Lost in Transit</fullName>
            </value>
            <value>
                <fullName>Incorrect Addresses</fullName>
            </value>
            <value>
                <fullName>Customer Unreachable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Refer_Back_Reason__c.field-meta.xml
<CustomField>
    <fullName>Refer_Back_Reason__c</fullName>
    <label>Refer Back Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Resolved</fullName>
            </value>
            <value>
                <fullName>Need More Info</fullName>
            </value>
            <value>
                <fullName>Send Update</fullName>
            </value>
            <value>
                <fullName>Wrongly Sent</fullName>
            </value>
            <value>
                <fullName>Address Changed</fullName>
                <isActive>false</isActive>
                <label>Address Changed</label>
            </value>
            <value>
                <fullName>Cancellation Processed</fullName>
                <isActive>false</isActive>
                <label>Cancellation Processed</label>
            </value>
            <value>
                <fullName>Cancellation Rejected</fullName>
                <isActive>false</isActive>
                <label>Cancellation Rejected</label>
            </value>
            <value>
                <fullName>Refund Processed</fullName>
                <isActive>false</isActive>
                <label>Refund Processed</label>
            </value>
            <value>
                <fullName>Refund Rejected</fullName>
                <isActive>false</isActive>
                <label>Refund Rejected</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Refund_Reason__c.field-meta.xml
<CustomField>
    <fullName>Refund_Reason__c</fullName>
    <label>Refund Reason</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Case/fields/Refund_Reasons__c.field-meta.xml
<CustomField>
    <fullName>Refund_Reasons__c</fullName>
    <label>Refund Reasons</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Product Defect</fullName>
            </value>
            <value>
                <fullName>Wrong Item Shipped</fullName>
            </value>
            <value>
                <fullName>Customer Changed Mind</fullName>
            </value>
            <value>
                <fullName>Late Delivery</fullName>
            </value>
            <value>
                <fullName>Item Not as Described</fullName>
            </value>
            <value>
                <fullName>Billing Error</fullName>
            </value>
            <value>
                <fullName>Cancelled Order</fullName>
            </value>
            <value>
                <fullName>Duplicate Order</fullName>
            </value>
            <value>
                <fullName>Unwanted Gift</fullName>
            </value>
            <value>
                <fullName>Other (Specify)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Refund_Type__c.field-meta.xml
<CustomField>
    <fullName>Refund_Type__c</fullName>
    <label>Refund Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Partial</fullName>
            </value>
            <value>
                <fullName>Full</fullName>
            </value>
            <value>
                <fullName>Special Case Refund</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Sub_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Sub_Sub_Type__c</fullName>
    <label>Sub Sub Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sub_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Login issues/Login number error</fullName>
            </value>
            <value>
                <fullName>Invalid Email/Phone Number</fullName>
            </value>
            <value>
                <fullName>Invalid Coupon Code</fullName>
            </value>
            <value>
                <fullName>App Stuck or Hanged</fullName>
            </value>
            <value>
                <fullName>Error while adding in cart</fullName>
            </value>
            <value>
                <fullName>Product Description/Offer Issues</fullName>
            </value>
            <value>
                <fullName>Addition of More Payment options or COD</fullName>
            </value>
            <value>
                <fullName>Refund Issues</fullName>
            </value>
            <value>
                <fullName>Change in profile number</fullName>
            </value>
            <value>
                <fullName>Updation of new email id</fullName>
            </value>
            <value>
                <fullName>Change in mail id</fullName>
            </value>
            <value>
                <fullName>Process to add/update more addresses</fullName>
            </value>
            <value>
                <fullName>Guided on App</fullName>
            </value>
            <value>
                <fullName>Price mismatch</fullName>
            </value>
            <value>
                <fullName>Comparison with Competitor</fullName>
            </value>
            <value>
                <fullName>Ongoing Campaign/Sales updates</fullName>
            </value>
            <value>
                <fullName>Upcoming Campaign /Sales updates</fullName>
            </value>
            <value>
                <fullName>How to check product review</fullName>
            </value>
            <value>
                <fullName>Giveaway inquiry</fullName>
            </value>
            <value>
                <fullName>Use of Coupon codes</fullName>
            </value>
            <value>
                <fullName>Coupon/Freebie /Discount/Cashback Issuance</fullName>
            </value>
            <value>
                <fullName>Gift an Order</fullName>
            </value>
            <value>
                <fullName>Information Given</fullName>
            </value>
            <value>
                <fullName>Guided to explore personalization on app</fullName>
            </value>
            <value>
                <fullName>Collabration Request/Influencer queries</fullName>
            </value>
            <value>
                <fullName>Collabration service issues</fullName>
            </value>
            <value>
                <fullName>Collabration Request</fullName>
            </value>
            <value>
                <fullName>Content Issues - Cx</fullName>
            </value>
            <value>
                <fullName>Content Issues - Partners</fullName>
            </value>
            <value>
                <fullName>Order number confirmation</fullName>
            </value>
            <value>
                <fullName>Order Confirmation /Status Issues</fullName>
            </value>
            <value>
                <fullName>Full</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Sub_Type__c</fullName>
    <label>Sub Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Order Related</fullName>
            </value>
            <value>
                <fullName>App Related</fullName>
            </value>
            <value>
                <fullName>Refund Issues</fullName>
            </value>
            <value>
                <fullName>Mobile number change</fullName>
            </value>
            <value>
                <fullName>Update Email id</fullName>
            </value>
            <value>
                <fullName>Process to add or update more addresses</fullName>
            </value>
            <value>
                <fullName>Product Price</fullName>
            </value>
            <value>
                <fullName>Comparison with Competitor</fullName>
            </value>
            <value>
                <fullName>Offers and Promotions</fullName>
            </value>
            <value>
                <fullName>Gift / Pre-book</fullName>
            </value>
            <value>
                <fullName>Process to Purchase / Delivery Charges</fullName>
            </value>
            <value>
                <fullName>Expected Delivery TAT / Preferred Delivery window</fullName>
            </value>
            <value>
                <fullName>Previous order OOS Req for benefit/code</fullName>
            </value>
            <value>
                <fullName>Missed campaign Req. for Benefit/code</fullName>
            </value>
            <value>
                <fullName>Word of Mouth on Order Cancellation</fullName>
            </value>
            <value>
                <fullName>Know more about products</fullName>
            </value>
            <value>
                <fullName>Product Suitability</fullName>
            </value>
            <value>
                <fullName>Product Quantity or Ingredients or Description</fullName>
            </value>
            <value>
                <fullName>Stock / Restock</fullName>
            </value>
            <value>
                <fullName>Product life /Expiry/Authencity /Others</fullName>
            </value>
            <value>
                <fullName>Collaboration Request/Influencer queries</fullName>
            </value>
            <value>
                <fullName>Collaboration service issues</fullName>
            </value>
            <value>
                <fullName>Collaboration Request</fullName>
            </value>
            <value>
                <fullName>Content Issues - Cx</fullName>
            </value>
            <value>
                <fullName>Content Issues - Partners</fullName>
            </value>
            <value>
                <fullName>Order Status</fullName>
            </value>
            <value>
                <fullName>Gift Before Shipping</fullName>
            </value>
            <value>
                <fullName>Gift After Shipping</fullName>
            </value>
            <value>
                <fullName>Cancellation Before Shipping</fullName>
            </value>
            <value>
                <fullName>Cancellation After Shipping</fullName>
            </value>
            <value>
                <fullName>Full</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/UTR_Number__c.field-meta.xml
<CustomField>
    <fullName>UTR_Number__c</fullName>
    <label>UTR Number</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Progress_Detail__c/Case_Progress_Detail__c.object-meta.xml
<CustomObject>
    <label>Case Progress Detail</label>
    <nameField>
        <displayFormat>CPD-{0000}</displayFormat>
        <label>Case Progress Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Progress Details</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Progress_Detail__c/fields/Current_Action__c.field-meta.xml
<CustomField>
    <fullName>Current_Action__c</fullName>
    <label>Current Action</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Case_Progress_Detail__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Resolved</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Responded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/referBackToCsTeamControllerTest.cls
@isTest(seeAllData = true)
public class referBackToCsTeamControllerTest {
    @istest 
    static void testClass(){
        
        Profile pro = [SELECT Id,Name FROM Profile WHERE Name='Customer Service Executive']; 
        
        User userInstant = new User(Alias = 'standt', Email='sossfdc@cirrologix.com', 
                                    EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
                                    IsActive=true,Division='Rainmakers',
                                    LocaleSidKey='en_US', ProfileId = pro.Id,
                                    TimeZoneSidKey='America/Los_Angeles', UserName='standardVarsha@testorg.com');
        insert userInstant;
        
        Account acc = new Account();
        acc.Name = 'Testing';
        acc.Phone = '098765432123456';
        Insert acc;
        
        Contact con = new Contact();
        con.accountId = acc.Id;
        con.Email = 'new@contact.com';
        con.FirstName = 'Test';
        con.LastName = 'contact';
        Insert Con;
        
        Product2 objProduct = new Product2();
        objProduct.Name = 'Tesrtt';
        objProduct.Description = 'Tesrt';
        Insert objProduct;
        
        Pricebook2 pb = new Pricebook2(Name = 'Standard Price Book 2009', Description = 'Price Book 2009 Products', IsActive = true );
        insert pb;
        Product2 prod = new Product2(Name = 'SLA: Bronze', IsActive = true);
        insert prod;
        // First insert a price for the standard price book
        Pricebook2 standardPB = [select id from Pricebook2 where isStandard=true];
        PricebookEntry standardPBE = new PricebookEntry(Pricebook2Id = standardPB.Id, Product2Id = prod.Id, UnitPrice = 1000, IsActive = true);
        insert standardPBE;
        PricebookEntry pbe = new PricebookEntry(Pricebook2Id = pb.Id, Product2Id = prod.Id, UnitPrice = 1000, IsActive = true);
        insert pbe;
        
        Order ord = new order();
        ord.AccountId = acc.Id;
        ord.EffectiveDate = system.today();
        ord.Status = 'Draft';
        ord.Pricebook2Id = pb.id;
        ord.UTR_Number__c = '123456';
        Insert ord;
        
        List<OrderItem> orItmList = new List<OrderItem>();        
        OrderItem ordItm = new OrderItem();
        ordItm.OrderId = ord.Id;
        ordItm.UnitPrice = 200;
        ordItm.PricebookEntryId = pbe.Id;
        ordItm.Quantity = 1;
        ordItm.SKU__c = 'Test';
        orItmList.add(ordItm);
        Insert orItmList;
        
        Map<Id,Case> mapOfCase = new Map<Id,Case>();
        Case cse = new Case();
        cse.Origin = 'Bulk Upload';
        cse.Status = 'New';
        cse.AccountId = acc.Id;
        cse.OrderId__c = ord.Id;
        cse.ContactId = con.Id;
        cse.Inital_Commented_Date__c = system.today();
        cse.subject = 'Testing';
        cse.Refund_Type__c = 'Full';
        cse.Refund_Reasons__c = 'Customer Changed Mind';   
        cse.Refund_Reason__c = 'Testing';
        cse.Sub_Type__c = 'Order Related';
        cse.Sub_Sub_Type__c = 'Order Confirmation /Status Issues';
        cse.Reason_For_Dealy__c = 'Customer Unreachable';
        cse.OwnerId = userInstant.Id;
        Insert cse;
        cse.Reason_For_Dealy__c = 'Lost in Transit';
        update cse;
        mapOfCase.put(cse.Id,cse);
        
        Map<Id,Case> mapOfCase1 = new Map<Id,Case>();
        Case cse1 = new Case();
        cse1.Origin = 'Bulk Upload';
        cse1.Status = 'New';
        cse1.AccountId = acc.Id;
        cse1.OrderId__c = ord.Id;
        cse1.ContactId = con.Id;
        cse1.Inital_Commented_Date__c = system.today();
        cse1.subject = 'Testing';
        cse1.Refund_Type__c = 'Full';
        cse1.Refund_Reasons__c = 'Customer Changed Mind';   
        cse1.Refund_Reason__c = 'Testing';
        cse1.Type = 'Order Related';
        cse1.Sub_Type__c = 'Order Related';
        cse1.Sub_Sub_Type__c = 'Order Confirmation /Status Issues';
        cse1.Reason_For_Dealy__c = 'Lost in Transit';
        Insert cse1;
        cse1.Reason_For_Dealy__c = 'Incorrect Addresses';
        update cse1;
        mapOfCase1.put(cse1.Id,cse1);
        
        Map<Id,Case> mapOfCase2 = new Map<Id,Case>();
        Case cse2 = new Case();
        cse2.Origin = 'Bulk Upload';
        cse2.Status = 'New';
        cse2.AccountId = acc.Id;
        cse2.OrderId__c = ord.Id;
        cse2.ContactId = con.Id;
        cse2.Inital_Commented_Date__c = system.today();
        cse2.subject = 'Testing';
        cse2.Refund_Type__c = 'Special Case Refund';
        cse2.Refund_Reasons__c = 'Customer Changed Mind';   
        cse2.Refund_Reason__c = 'Testing';
        cse2.Type = 'Order Related';
        cse2.Sub_Type__c = 'Order Related';
        cse2.Sub_Sub_Type__c = 'Order Confirmation /Status Issues';
        cse2.Reason_For_Dealy__c = 'Lost in Transit';
        cse2.Refer_Back_Reason__c = 'Send Update';
        cse2.Approval_Remarks__c = 'qwetyu';
        cse2.Rejection_Reason__c = 'qwtuirdx';
        cse2.Describe_Information_Needed__c = 'qwertyu';
        Insert cse2;
        cse2.Reason_For_Dealy__c = 'Customer Unreachable';
        update cse2;
        mapOfCase2.put(cse2.Id,cse2);
        
        Map<Id, Case> mapOfCase3 = new Map<Id, Case>();
        Case cse3 = new Case();
        cse3.Origin = 'Bulk Upload';
        cse3.Status = 'New';
        cse3.AccountId = acc.Id;
        cse3.OrderId__c = ord.Id;
        cse3.ContactId = con.Id;
        cse3.Inital_Commented_Date__c = system.today();
        cse3.subject = 'Testing';
        cse3.Refund_Type__c = 'Full';
        cse3.Refund_Reasons__c = 'Customer Changed Mind';
        cse3.Refund_Reason__c = 'Testing';
        cse3.Type = 'Order Related';
        cse3.Sub_Type__c = 'Order Related';
        cse3.Sub_Sub_Type__c = 'Order Confirmation /Status Issues';
        cse3.Reason_For_Dealy__c = 'Lost in Transit';
        cse3.Refer_Back_Reason__c = 'Send Update';
        cse3.Approval_Remarks__c = 'qwetyu';
        cse3.Rejection_Reason__c = 'qwtuirdx';
        cse3.Describe_Information_Needed__c = 'qwertyu';
        Insert cse3;
        cse3.Reason_For_Dealy__c = 'Customer Unreachable';
        update cse3;
        mapOfCase3.put(cse3.Id, cse3);
        
        
        Task newTask = new Task();
        newTask.Subject = 'Case has been assigned to Move to Refund Team';
        newTask.Description = 'Please Move To Refund Team case with case ID: ' + cse.Id;
        newTask.WhatId = cse.Id; 
        
        insert newTask;
        
        List<Case_Progress_Detail__c> listcpd = new List<Case_Progress_Detail__c>();
        Case_Progress_Detail__c cpd1 = new Case_Progress_Detail__c();
        cpd1.Status__c ='Open';
        cpd1.Current_Action__c = 'Case Update Sent';
        cpd1.Response_Time__c =System.Now();
        cpd1.Current_Action__c = 'Case Update Sent';
        cpd1.Case__c = cse.Id;       
        listcpd.add(cpd1);
        insert listcpd;
        
        List<Case_Progress_Detail__c> listcpd1 = new List<Case_Progress_Detail__c>();
        Case_Progress_Detail__c cpd2 = new Case_Progress_Detail__c();
        cpd2.Status__c ='Open';
        cpd2.Current_Action__c = 'Case Update Sent';
        cpd2.Response_Time__c =System.Now();
        cpd2.Current_Action__c = 'Case Update Sent';
        cpd2.Case__c = cse2.Id;       
        listcpd.add(cpd2);
        insert listcpd1;
        
        
        list<Account> lsacc = new list<Account>();
        Account acc1 = new Account();
        acc1.Name = 'Testing';
        acc1.Phone = '098765432123456';
        lsacc.add(acc1);
        insert lsacc;
        
        Refund_API_Details__c refundSettings = new Refund_API_Details__c();
        refundSettings.Endpoint__c = 'https://ops.dev.kult.in/api/v1/order/process_refund';
        refundSettings.Access_Token__c = 'Bearer dummy_access_token';
        //insert refundSettings;
        
        // Create Affected_SKU__c records
        Affected_SKU__c affectedSKU1 = new Affected_SKU__c(
            Case__c = cse2.Id, 
            Name = 'SKU001', 
            Order_Item__c = ordItm.Id
        );
        Affected_SKU__c affectedSKU2 = new Affected_SKU__c(
            Case__c = cse.Id, 
            Name = 'SKU002', 
            Order_Item__c = ordItm.Id
        );
        
        List<Affected_SKU__c> affSKUstoInsert = new List<Affected_SKU__c>();
        affSKUstoInsert.add(affectedSKU1);
        affSKUstoInsert.add(affectedSKU2);
        insert affSKUstoInsert;
        
        // Testing the methods
        Test.startTest();
        referBackToCsTeamController.getCaseById(cse.Id);
        referBackToCsTeamController.getCaseTeamAndType(cse.Id);
        referBackToCsTeamController.getCaseAndOrderDetails(cse.Id, 'Send Update', 200, 'qwetyu', 'qwtuirdx', cse2.Describe_Information_Needed__c, 200, 'resolution remarks', 'update desc', 'base64String', 'filename', 'awbNumber', 'focOrderId','Crash Issues',True);
        referBackToCsTeamController.getCaseAndOrderDetails(cse1.Id, 'Need More Info', 200, 'qwetyu', 'qwtuirdx', cse2.Describe_Information_Needed__c, 200, 'resolution remarks', 'update desc', 'base64String', 'filename', 'awbNumber', 'focOrderId','Crash Issues',True);
        referBackToCsTeamController.getCaseAndOrderDetails(cse2.Id, 'Send Update', 200, 'qwetyu', 'qwtuirdx', cse2.Describe_Information_Needed__c, 200, 'resolution remarks', 'update desc', 'base64String', 'filename', 'awbNumber', 'focOrderId','Crash Issues',True);
        referBackToCsTeamController.getCaseAndOrderDetails(cse.Id, 'Resolved', 200, 'qwetyu', 'qwtuirdx', cse2.Describe_Information_Needed__c, 200, 'resolution remarks', 'update desc', 'base64String', 'filename', 'awbNumber', 'focOrderId','Crash Issues',True);
        referBackToCsTeamController.getCaseAndOrderDetails(cse2.Id, 'Resolved', 200, 'qwetyu', 'qwtuirdx', cse2.Describe_Information_Needed__c, 200, 'resolution remarks', 'update desc', 'base64String', 'filename', 'awbNumber', 'focOrderId','Crash Issues',True);
        referBackToCsTeamController.getCaseAndOrderDetails(cse3.Id, 'Resolved', 200, 'qwetyu', 'qwtuirdx', cse2.Describe_Information_Needed__c, 200, 'resolution remarks', 'update desc', 'base64String', 'filename', 'awbNumber', 'focOrderId','Crash Issues',True);
        referBackToCsTeamController.deletecaseShares(cse.Id);
        referBackToCsTeamController.sendingCustomNotification(userInstant.Id, cse.Id, 'Test Class Title', 'Test Class Body', new List<String>{'anwarchikle2000@gmail.com'});
        referBackToCsTeamController.AccountCreatedConCreated(lsacc);
        Test.stopTest();
    } 
    
    @isTest
    static void testPostRefundRequest() {
        // Mock HTTP response for the callout
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        
        // Get a Case Id for testing
        Case testCase = [SELECT Id FROM Case LIMIT 1];
        
        // Call the method
        String result = CalloutRefundAPIClass.postRefundRequest(testCase.Id);
        
    }
    
    
    /* @istest 
static void testClass1(){
Profile pro = [SELECT Id,Name FROM Profile WHERE Name='WareHouse Team']; 

User userInstant = new User(Alias = 'standt', Email='sossfdc@cirrologix.com', 
EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
IsActive=true,Division='Rainmakers',
LocaleSidKey='en_US', ProfileId = pro.Id,
TimeZoneSidKey='America/Los_Angeles', UserName='standardVarsha@testorg.com');
insert userInstant;

Account acc = new Account();
acc.Name = 'Testing';
acc.Phone = '098765432123456';
Insert acc;

Contact con = new Contact();
con.accountId = acc.Id;
con.Email = 'new@contact.com';
con.FirstName = 'Test';
con.LastName = 'contact';
Insert Con;

Product2 objProduct = new Product2();
objProduct.Name = 'Tesrtt';
objProduct.Description = 'Tesrt';
Insert objProduct;

Pricebook2 pb = new Pricebook2(Name = 'Standard Price Book 2009', Description = 'Price Book 2009 Products', IsActive = true );
insert pb;
Product2 prod = new Product2(Name = 'SLA: Bronze', IsActive = true);
insert prod;
// First insert a price for the standard price book
Pricebook2 standardPB = [select id from Pricebook2 where isStandard=true];
PricebookEntry standardPBE = new PricebookEntry(Pricebook2Id = standardPB.Id, Product2Id = prod.Id, UnitPrice = 1000, IsActive = true);
insert standardPBE;
PricebookEntry pbe = new PricebookEntry(Pricebook2Id = pb.Id, Product2Id = prod.Id, UnitPrice = 1000, IsActive = true);
insert pbe;

Order ord = new order();
ord.AccountId = acc.Id;
ord.EffectiveDate = system.today();
ord.Status = 'Draft';
ord.Pricebook2Id = pb.id;
ord.UTR_Number__c = '123456';
Insert ord;

List<OrderItem> orItmList = new List<OrderItem>();        
OrderItem ordItm = new OrderItem();
ordItm.OrderId = ord.Id;
ordItm.UnitPrice = 200;
ordItm.PricebookEntryId = pbe.Id;
ordItm.Quantity = 1;
ordItm.SKU__c = 'Test';
orItmList.add(ordItm);
Insert orItmList;

Map<Id,Case> mapOfCase = new Map<Id,Case>();
Case cse = new Case();
cse.Origin = 'Bulk Upload';
cse.Status = 'New';
cse.AccountId = acc.Id;
cse.OrderId__c = ord.Id;
cse.ContactId = con.Id;
cse.Inital_Commented_Date__c = system.today();
cse.subject = 'Testing';
cse.Refund_Type__c = 'Full';
cse.Refund_Reasons__c = 'Customer Changed Mind';   
cse.Refund_Reason__c = 'Testing';
cse.Sub_Type__c = 'Order Related';
cse.Sub_Sub_Type__c = 'Order Confirmation /Status Issues';
cse.Reason_For_Dealy__c = 'Customer Unreachable';
Insert cse;
cse.Reason_For_Dealy__c = 'Lost in Transit';
update cse;
mapOfCase.put(cse.Id,cse);

Map<Id,Case> mapOfCase1 = new Map<Id,Case>();
Case cse1 = new Case();
cse1.Origin = 'Bulk Upload';
cse1.Status = 'New';
cse1.AccountId = acc.Id;
//cse1.OrderId__c = ord.Id;
cse1.ContactId = con.Id;
cse1.Inital_Commented_Date__c = system.today();
cse1.subject = 'Testing';
cse1.Refund_Type__c = 'Full';
cse1.Refund_Reasons__c = 'Customer Changed Mind';   
cse1.Refund_Reason__c = 'Testing';
cse1.Type = 'Order Related';
cse1.Sub_Type__c = 'Order Related';
// cse1.Sub_Sub_Type__c = 'Order Confirmation /Status Issues';
cse1.Reason_For_Dealy__c = 'Lost in Transit';
Insert cse1;
cse1.Reason_For_Dealy__c = 'Incorrect Addresses';
update cse1;
mapOfCase1.put(cse1.Id,cse1);

Map<Id,Case> mapOfCase2 = new Map<Id,Case>();
Case cse2 = new Case();
cse2.Origin = 'Bulk Upload';
cse2.Status = 'New';
cse2.AccountId = acc.Id;
cse2.OrderId__c = ord.Id;
cse2.ContactId = con.Id;
cse2.Inital_Commented_Date__c = system.today();
cse2.subject = 'Testing';
cse2.Refund_Type__c = 'Full';
cse2.Refund_Reasons__c = 'Customer Changed Mind';   
cse2.Refund_Reason__c = 'Testing';
cse2.Type = 'Order Related';
cse2.Sub_Type__c = 'Order Related';
cse2.Sub_Sub_Type__c = 'Order Confirmation /Status Issues';
cse2.Reason_For_Dealy__c = 'Lost in Transit';
cse2.Refer_Back_Reason__c = 'Send Update';
cse2.Approval_Remarks__c = 'qwetyu';
cse2.Rejection_Reason__c = 'qwtuirdx';
cse2.Describe_Information_Needed__c = 'qwertyu';
Insert cse2;
cse2.Reason_For_Dealy__c = 'Customer Unreachable';
update cse2;
mapOfCase2.put(cse2.Id,cse2);

Task newTask = new Task();
newTask.Subject = 'Case has been assigned to Move to Refund Team';
newTask.Description = 'Please Move To Refund Team case with case ID: ' + cse.Id;
newTask.WhatId = cse.Id; 

insert newTask;

list<Account> lsacc = new list<Account>();
Account acc1 = new Account();
acc1.Name = 'Testing';
acc1.Phone = '098765432123456';
lsacc.add(acc1);
insert lsacc;

// Testing the methods
Test.startTest();
referBackToCsTeamController.getCaseById(cse.Id);
referBackToCsTeamController.getCaseTeamAndType(cse.Id);
referBackToCsTeamController.getCaseAndOrderDetails(cse.Id, cse2.Refer_Back_Reason__c, 200, cse2.Approval_Remarks__c, cse2.Rejection_Reason__c, cse2.Describe_Information_Needed__c, 200, 'resolution remarks', 'update desc', 'base64String', 'filename', 'awbNumber', 'focOrderId','Crash Issues',True);
referBackToCsTeamController.deletecaseShares(cse.Id);
referBackToCsTeamController.sendingCustomNotification(userInstant.Id, cse.Id, 'Test Class Title', 'Test Class Body', new List<String>{'anwarchikle2000@gmail.com'});
referBackToCsTeamController.AccountCreatedConCreated(lsacc);
Test.stopTest();
} 

@istest 
static void testClass2(){
Profile pro = [SELECT Id,Name FROM Profile WHERE Name='WareHouse Team']; 

User userInstant = new User(Alias = 'standt', Email='sossfdc@cirrologix.com', 
EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
IsActive=true,Division='Rainmakers',
LocaleSidKey='en_US', ProfileId = pro.Id,
TimeZoneSidKey='America/Los_Angeles', UserName='standardVarsha@testorg.com');
insert userInstant;

Account acc = new Account();
acc.Name = 'Testing';
acc.Phone = '098765432123456';
Insert acc;

Contact con = new Contact();
con.accountId = acc.Id;
con.Email = 'new@contact.com';
con.FirstName = 'Test';
con.LastName = 'contact';
Insert Con;

Product2 objProduct = new Product2();
objProduct.Name = 'Tesrtt';
objProduct.Description = 'Tesrt';
Insert objProduct;

Pricebook2 pb = new Pricebook2(Name = 'Standard Price Book 2009', Description = 'Price Book 2009 Products', IsActive = true );
insert pb;
Product2 prod = new Product2(Name = 'SLA: Bronze', IsActive = true);
insert prod;
// First insert a price for the standard price book
Pricebook2 standardPB = [select id from Pricebook2 where isStandard=true];
PricebookEntry standardPBE = new PricebookEntry(Pricebook2Id = standardPB.Id, Product2Id = prod.Id, UnitPrice = 1000, IsActive = true);
insert standardPBE;
PricebookEntry pbe = new PricebookEntry(Pricebook2Id = pb.Id, Product2Id = prod.Id, UnitPrice = 1000, IsActive = true);
insert pbe;

Order ord = new order();
ord.AccountId = acc.Id;
ord.EffectiveDate = system.today();
ord.Status = 'Draft';
ord.Pricebook2Id = pb.id;
ord.UTR_Number__c = '123456';
Insert ord;

List<OrderItem> orItmList = new List<OrderItem>();        
OrderItem ordItm = new OrderItem();
ordItm.OrderId = ord.Id;
ordItm.UnitPrice = 200;
ordItm.PricebookEntryId = pbe.Id;
ordItm.Quantity = 1;
ordItm.SKU__c = 'Test';
orItmList.add(ordItm);
Insert orItmList;

Map<Id,Case> mapOfCase = new Map<Id,Case>();
Case cse = new Case();
cse.Origin = 'Bulk Upload';
cse.Status = 'New';
cse.AccountId = acc.Id;
cse.OrderId__c = ord.Id;
cse.ContactId = con.Id;
cse.Inital_Commented_Date__c = system.today();
cse.subject = 'Testing';
cse.Refund_Type__c = 'Full';
cse.Refund_Reasons__c = 'Customer Changed Mind';   
cse.Refund_Reason__c = 'Testing';
cse.Sub_Type__c = 'Order Related';
cse.Sub_Sub_Type__c = 'Order Confirmation /Status Issues';
cse.Reason_For_Dealy__c = 'Customer Unreachable';
Insert cse;
cse.Reason_For_Dealy__c = 'Lost in Transit';
update cse;
mapOfCase.put(cse.Id,cse);

Map<Id,Case> mapOfCase1 = new Map<Id,Case>();
Case cse1 = new Case();
cse1.Origin = 'Bulk Upload';
cse1.Status = 'New';
cse1.AccountId = acc.Id;
cse1.OrderId__c = ord.Id;
cse1.ContactId = con.Id;
cse1.Inital_Commented_Date__c = system.today();
cse1.subject = 'Testing';
cse1.Refund_Type__c = 'Full';
cse1.Refund_Reasons__c = 'Customer Changed Mind';   
cse1.Refund_Reason__c = 'Testing';
cse1.Type = 'Order Related';
cse1.Sub_Type__c = 'Order Related';
cse1.Sub_Sub_Type__c = 'Order Confirmation /Status Issues';
cse1.Reason_For_Dealy__c = 'Lost in Transit';
Insert cse1;
cse1.Reason_For_Dealy__c = 'Incorrect Addresses';
update cse1;
mapOfCase1.put(cse1.Id,cse1);

Map<Id,Case> mapOfCase2 = new Map<Id,Case>();
Case cse2 = new Case();
cse2.Origin = 'Bulk Upload';
cse2.Status = 'New';
cse2.AccountId = acc.Id;
cse2.OrderId__c = ord.Id;
cse2.ContactId = con.Id;
cse2.Inital_Commented_Date__c = system.today();
cse2.subject = 'Testing';
cse2.Refund_Type__c = 'Full';
cse2.Refund_Reasons__c = 'Customer Changed Mind';   
cse2.Refund_Reason__c = 'Testing';
cse2.Type = 'Order Related';
cse2.Sub_Type__c = 'Order Related';
cse2.Sub_Sub_Type__c = 'Order Confirmation /Status Issues';
cse2.Reason_For_Dealy__c = 'Lost in Transit';
cse2.Refer_Back_Reason__c = 'Resolved';
cse2.Approval_Remarks__c = 'qwetyu';
cse2.Rejection_Reason__c = 'qwtuirdx';
cse2.Describe_Information_Needed__c = 'qwertyu';
Insert cse2;
cse2.Reason_For_Dealy__c = 'Customer Unreachable';
update cse2;
mapOfCase2.put(cse2.Id,cse2);

Task newTask = new Task();
newTask.Subject = 'Case has been assigned to Move to Refund Team';
newTask.Description = 'Please Move To Refund Team case with case ID: ' + cse.Id;
newTask.WhatId = cse.Id; 

insert newTask;

list<Account> lsacc = new list<Account>();
Account acc1 = new Account();
acc1.Name = 'Testing';
acc1.Phone = '098765432123456';
lsacc.add(acc1);
insert lsacc;

// Testing the methods
Test.startTest();
referBackToCsTeamController.getCaseById(cse.Id);
referBackToCsTeamController.getCaseTeamAndType(cse.Id);
referBackToCsTeamController.getCaseAndOrderDetails(cse.Id, cse2.Refer_Back_Reason__c, 200, cse2.Approval_Remarks__c, cse2.Rejection_Reason__c, cse2.Describe_Information_Needed__c, 200, 'resolution remarks', 'update desc', 'base64String', 'filename', 'awbNumber', 'focOrderId','Crash Issues',True);
referBackToCsTeamController.deletecaseShares(cse.Id);
referBackToCsTeamController.sendingCustomNotification(userInstant.Id, cse.Id, 'Test Class Title', 'Test Class Body', new List<String>{'anwarchikle2000@gmail.com'});
referBackToCsTeamController.AccountCreatedConCreated(lsacc);
Test.stopTest();  

} 

@isTest
static void testClasses(){


Profile pro = [SELECT Id,Name FROM Profile WHERE Name='Customer Service Executive']; 

User userInstant = new User(Alias = 'standt', Email='sossfdc@cirrologix.com', 
EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
IsActive=true,Division='Rainmakers',
LocaleSidKey='en_US', ProfileId = pro.Id,
TimeZoneSidKey='America/Los_Angeles', UserName='standardVarsha@testorg.com');
insert userInstant;

Account acc = new Account();
acc.Name = 'Testing';
acc.Phone = '098765432123456';
Insert acc;

Contact con = new Contact();
con.accountId = acc.Id;
con.Email = 'new@contact.com';
con.FirstName = 'Test';
con.LastName = 'contact';
Insert Con;

Product2 objProduct = new Product2();
objProduct.Name = 'Tesrtt';
objProduct.Description = 'Tesrt';
Insert objProduct;

Pricebook2 pb = new Pricebook2(Name = 'Standard Price Book 2009', Description = 'Price Book 2009 Products', IsActive = true );
insert pb;
Product2 prod = new Product2(Name = 'SLA: Bronze', IsActive = true);
insert prod;
// First insert a price for the standard price book
Pricebook2 standardPB = [select id from Pricebook2 where isStandard=true];
PricebookEntry standardPBE = new PricebookEntry(Pricebook2Id = standardPB.Id, Product2Id = prod.Id, UnitPrice = 1000, IsActive = true);
insert standardPBE;
PricebookEntry pbe = new PricebookEntry(Pricebook2Id = pb.Id, Product2Id = prod.Id, UnitPrice = 1000, IsActive = true);
insert pbe;

Order ord = new order();
ord.AccountId = acc.Id;
ord.EffectiveDate = system.today();
ord.Status = 'Draft';
ord.Pricebook2Id = pb.id;
ord.UTR_Number__c = '123456';
Insert ord;

List<OrderItem> orItmList = new List<OrderItem>();        
OrderItem ordItm = new OrderItem();
ordItm.OrderId = ord.Id;
ordItm.UnitPrice = 200;
ordItm.PricebookEntryId = pbe.Id;
ordItm.Quantity = 1;
ordItm.SKU__c = 'Test';
orItmList.add(ordItm);
Insert orItmList;

Map<Id,Case> mapOfCase = new Map<Id,Case>();
Case cse = new Case();
cse.Origin = 'Bulk Upload';
cse.Status = 'New';
cse.AccountId = acc.Id;
cse.OrderId__c = ord.Id;
cse.ContactId = con.Id;
cse.Inital_Commented_Date__c = system.today();
cse.subject = 'Testing';
cse.Refund_Type__c = 'Full';
cse.Refund_Reasons__c = 'Customer Changed Mind';   
cse.Refund_Reason__c = 'Testing';
cse.Sub_Type__c = 'Order Related';
cse.Sub_Sub_Type__c = 'Order Confirmation /Status Issues';
cse.Reason_For_Dealy__c = 'Customer Unreachable';
cse.OwnerId = userInstant.Id;
Insert cse;
cse.Reason_For_Dealy__c = 'Lost in Transit';
update cse;
mapOfCase.put(cse.Id,cse);

List<Case_Progress_Detail__c> listcpd = new List<Case_Progress_Detail__c>();
Case_Progress_Detail__c cpd1 = new Case_Progress_Detail__c();
cpd1.Status__c ='Open';
cpd1.Current_Action__c = 'Case Update Sent';
cpd1.Response_Time__c =System.Now();
cpd1.Current_Action__c = 'Case Update Sent';
cpd1.Case__c = cse.Id;       
listcpd.add(cpd1);
insert listcpd;

// Testing the methods
Test.startTest();
referBackToCsTeamController.getCaseTeamAndType(cse.Id);
Test.stopTest();
} */
}