force-app/main/default/objects/Affected_SKU__c/Affected_SKU__c.object-meta.xml
<CustomObject>
    <label>Affected SKU</label>
    <nameField>
        <label>Affected SKU Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Affected SKUs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Affected_SKU__c/fields/Brand_Name__c.field-meta.xml
<CustomField>
    <fullName>Brand_Name__c</fullName>
    <label>Brand Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Affected_SKU__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Affected SKUs</relationshipLabel>
    <relationshipName>Affected_SKUs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Affected_SKU__c/fields/MRP__c.field-meta.xml
<CustomField>
    <fullName>MRP__c</fullName>
    <label>MRP</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Affected_SKU__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <label>Product Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Affected_SKU__c/fields/Refund_Amount__c.field-meta.xml
<CustomField>
    <fullName>Refund_Amount__c</fullName>
    <label>Refund Amount</label>
    <precision>15</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Affected_SKU__c/fields/Selling_Price__c.field-meta.xml
<CustomField>
    <fullName>Selling_Price__c</fullName>
    <label>Selling Price</label>
    <precision>9</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Case/fields/Brand_Name__c.field-meta.xml
<CustomField>
    <fullName>Brand_Name__c</fullName>
    <label>Brand Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Case_Sub_Status__c.field-meta.xml
<CustomField>
    <fullName>Case_Sub_Status__c</fullName>
    <label>Case Sub-Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Assigned to CS Team</fullName>
            </value>
            <value>
                <fullName>Assigned to Warehouse Team</fullName>
            </value>
            <value>
                <fullName>Assigned to Refund Team</fullName>
            </value>
            <value>
                <fullName>Assigned to Marketing Team</fullName>
            </value>
            <value>
                <fullName>Referred Back to CS Team</fullName>
            </value>
            <value>
                <fullName>Closed as Duplicate Case</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Contact_Number__c.field-meta.xml
<CustomField>
    <fullName>Contact_Number__c</fullName>
    <label>Contact Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Case/fields/Coupon__c.field-meta.xml
<CustomField>
    <fullName>Coupon__c</fullName>
    <label>Coupon</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/CS_Team_Member__c.field-meta.xml
<CustomField>
    <fullName>CS_Team_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CS Team Member</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Cases3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/OrderId__c.field-meta.xml
<CustomField>
    <fullName>OrderId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Order.Name</field>
            <operation>notContain</operation>
            <value>-</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Refund_Reason__c.field-meta.xml
<CustomField>
    <fullName>Refund_Reason__c</fullName>
    <label>Refund Reason</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Case/fields/Refund_Reasons__c.field-meta.xml
<CustomField>
    <fullName>Refund_Reasons__c</fullName>
    <label>Refund Reasons</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Product Defect</fullName>
            </value>
            <value>
                <fullName>Wrong Item Shipped</fullName>
            </value>
            <value>
                <fullName>Customer Changed Mind</fullName>
            </value>
            <value>
                <fullName>Late Delivery</fullName>
            </value>
            <value>
                <fullName>Item Not as Described</fullName>
            </value>
            <value>
                <fullName>Billing Error</fullName>
            </value>
            <value>
                <fullName>Cancelled Order</fullName>
            </value>
            <value>
                <fullName>Duplicate Order</fullName>
            </value>
            <value>
                <fullName>Unwanted Gift</fullName>
            </value>
            <value>
                <fullName>Other (Specify)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Refund_Type__c.field-meta.xml
<CustomField>
    <fullName>Refund_Type__c</fullName>
    <label>Refund Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Partial</fullName>
            </value>
            <value>
                <fullName>Full</fullName>
            </value>
            <value>
                <fullName>Special Case Refund</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/RefundTeamMember__c.field-meta.xml
<CustomField>
    <fullName>RefundTeamMember__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Refund Team Member</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Sub_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Sub_Sub_Type__c</fullName>
    <label>Sub Sub Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Sub_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Login issues/Login number error</fullName>
            </value>
            <value>
                <fullName>Invalid Email/Phone Number</fullName>
            </value>
            <value>
                <fullName>Invalid Coupon Code</fullName>
            </value>
            <value>
                <fullName>App Stuck or Hanged</fullName>
            </value>
            <value>
                <fullName>Error while adding in cart</fullName>
            </value>
            <value>
                <fullName>Product Description/Offer Issues</fullName>
            </value>
            <value>
                <fullName>Addition of More Payment options or COD</fullName>
            </value>
            <value>
                <fullName>Refund Issues</fullName>
            </value>
            <value>
                <fullName>Change in profile number</fullName>
            </value>
            <value>
                <fullName>Updation of new email id</fullName>
            </value>
            <value>
                <fullName>Change in mail id</fullName>
            </value>
            <value>
                <fullName>Process to add/update more addresses</fullName>
            </value>
            <value>
                <fullName>Guided on App</fullName>
            </value>
            <value>
                <fullName>Price mismatch</fullName>
            </value>
            <value>
                <fullName>Comparison with Competitor</fullName>
            </value>
            <value>
                <fullName>Ongoing Campaign/Sales updates</fullName>
            </value>
            <value>
                <fullName>Upcoming Campaign /Sales updates</fullName>
            </value>
            <value>
                <fullName>How to check product review</fullName>
            </value>
            <value>
                <fullName>Giveaway inquiry</fullName>
            </value>
            <value>
                <fullName>Use of Coupon codes</fullName>
            </value>
            <value>
                <fullName>Coupon/Freebie /Discount/Cashback Issuance</fullName>
            </value>
            <value>
                <fullName>Gift an Order</fullName>
            </value>
            <value>
                <fullName>Information Given</fullName>
            </value>
            <value>
                <fullName>Guided to explore personalization on app</fullName>
            </value>
            <value>
                <fullName>Collabration Request/Influencer queries</fullName>
            </value>
            <value>
                <fullName>Collabration service issues</fullName>
            </value>
            <value>
                <fullName>Collabration Request</fullName>
            </value>
            <value>
                <fullName>Content Issues - Cx</fullName>
            </value>
            <value>
                <fullName>Content Issues - Partners</fullName>
            </value>
            <value>
                <fullName>Order number confirmation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Sub_Type__c</fullName>
    <label>Sub Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Order Related</fullName>
            </value>
            <value>
                <fullName>App Related</fullName>
            </value>
            <value>
                <fullName>Refund Issues</fullName>
            </value>
            <value>
                <fullName>Mobile number change</fullName>
            </value>
            <value>
                <fullName>Update Email id</fullName>
            </value>
            <value>
                <fullName>Process to add or update more addresses</fullName>
            </value>
            <value>
                <fullName>Product Price</fullName>
            </value>
            <value>
                <fullName>Comparison with Competitor</fullName>
            </value>
            <value>
                <fullName>Offers and Promotions</fullName>
            </value>
            <value>
                <fullName>Gift / Pre-book</fullName>
            </value>
            <value>
                <fullName>Process to Purchase / Delivery Charges</fullName>
            </value>
            <value>
                <fullName>Expected Delivery TAT / Preferred Delivery window</fullName>
            </value>
            <value>
                <fullName>Previous order OOS Req for benefit/code</fullName>
            </value>
            <value>
                <fullName>Missed campaign Req. for Benefit/code</fullName>
            </value>
            <value>
                <fullName>Word of Mouth on Order Cancellation</fullName>
            </value>
            <value>
                <fullName>Know more about products</fullName>
            </value>
            <value>
                <fullName>Product Suitability</fullName>
            </value>
            <value>
                <fullName>Product Quantity or Ingredients or Description</fullName>
            </value>
            <value>
                <fullName>Stock / Restock</fullName>
            </value>
            <value>
                <fullName>Product life /Expiry/Authencity /Others</fullName>
            </value>
            <value>
                <fullName>Collaboration Request/Influencer queries</fullName>
            </value>
            <value>
                <fullName>Collaboration service issues</fullName>
            </value>
            <value>
                <fullName>Collaboration Request</fullName>
            </value>
            <value>
                <fullName>Content Issues - Cx</fullName>
            </value>
            <value>
                <fullName>Content Issues - Partners</fullName>
            </value>
            <value>
                <fullName>Order Status</fullName>
            </value>
            <value>
                <fullName>Gift Before Shipping</fullName>
            </value>
            <value>
                <fullName>Gift After Shipping</fullName>
            </value>
            <value>
                <fullName>Cancellation Before Shipping</fullName>
            </value>
            <value>
                <fullName>Cancellation After Shipping</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/moveToRefundTeamController.cls
public class moveToRefundTeamController {
    
    @AuraEnabled(cacheable=true)
    public static RefundWrapper getOrderLineItem(String caseId) { 
        
        List<Case> caseList = [SELECT Id,Contact_Number__c,RefundTeamMember__c, Sub_Type__c, Sub_Sub_Type__c, OrderId__c, OrderId__r.Name,OrderId__r.Refund_Type__c, OrderId__r.Refund_Reason__c, OrderId__r.Coupon__c,OrderId__r.Refund_Amount__c,OrderId__r.Paid_Amount__c 
                               FROM Case WHERE Id = :caseId];
        System.debug('caseList=====>'+caseList);
        
        if (!caseList.isEmpty()) {
            Case caseRecord = caseList[0];
            System.debug('caseRecord=====>'+caseRecord);
            
            Order orderRecord = caseRecord.OrderId__r;
            
            System.debug('orderRecord=====>'+orderRecord);
            
            List<OrderItem> orderItems = [SELECT Id, Product2.Name,Quantity,Is_Already_Utilized__c, Refund_Quantity__c,TotalPrice,Refund_Price__c,Refund_Reason__c,Refund_Reasons__c,Refund_Type__c,SKU__c, Total_Selling_Price__c, Selling_Price__c  FROM OrderItem WHERE OrderId = :orderRecord.Id];
            System.debug('orderItems=====>'+orderItems);
            return new RefundWrapper(caseRecord, orderRecord, orderItems);
        } else {
            return null;
        }
    } 
    
    @AuraEnabled
    public static String updateOrderAndCaseFields(String caseId, String caseRefund, String refundReason, String coupon,String refundValue,String refundTeamMemberId, integer refundamount,integer paidamount,String type,string subtype,List<OrderItem> orderItemsToUpdate) {
        String result;
        
        system.debug('caseId--->'+caseId);
        System.debug('caseRefund====>'+caseRefund);
        System.debug('refundReason====>'+refundReason);
        System.debug('coupon====>'+coupon);
        System.debug('refundTeamMemberId====>'+refundTeamMemberId);
        System.debug('paidamount=====>'+paidamount);
        System.debug('orderItemsToUpdate=====>'+orderItemsToUpdate);
        //System.debug('contactNumber====>'+contactNumber);
        
        try{
            String CSteamId;
            
            List<Case> caseList = [SELECT Id, OrderId__c, ownerId, AccountId, Status, ContactId, CS_Team_Member__c FROM Case WHERE Id = :caseId LIMIT 1];
            System.debug('caseList=====>'+caseList);
            
            if (!caseList.isEmpty()) {
                Case caseRecord = caseList[0];
                if(caseRecord.CS_Team_Member__c == null && string.valueOf(caseRecord.OwnerId).startsWith('005')){
                    caseRecord.CS_Team_Member__c = caseRecord.OwnerId;
                }
                CSteamId = caseRecord.CS_Team_Member__c;
                caseRecord.OwnerId = refundTeamMemberId;
                //caseRecord.RefundTeamMember__c = refundTeamMemberId;
                //caseRecord.Contact_Number__c = contactNumber;
                caseRecord.Refund_Type__c = caseRefund;
                caseRecord.Refund_Reasons__c = refundValue;
                caseRecord.Refund_Reason__c = refundReason;
                caseRecord.Case_Sub_Status__c = 'Assigned to Refund Team';
                if(caseRecord.Status == 'New'){
                    caseRecord.Status = 'In Progress'; 
                }
                update caseRecord;
                System.debug('caseRecord====>'+caseRecord);
                 System.debug('caseRecord.OrderId__c =======>'+caseRecord.OrderId__c);
                
                if(caseRecord.OrderId__c != null){
                    Order orderRecord = [SELECT Id,Refund_Type__c,Refund_Reason__c, Coupon__c, Refund_Amount__c, Paid_Amount__c FROM Order WHERE Id = :caseRecord.OrderId__c LIMIT 1];
                    orderRecord.Refund_Type__c = caseRefund;
                    orderRecord.Refund_Reason__c = refundReason;
                    orderRecord.Coupon__c = coupon;
                    orderRecord.Refund_Reasons__c = refundValue;
                    orderRecord.Refund_Amount__c = refundamount;
                    orderRecord.Paid_Amount__c = paidamount;
                    system.debug('orderRecord--->'+orderRecord);
                    
                    List<OrderItem> updateAllOrderItems = new List<OrderItem>();
                    List<Affected_SKU__c> affectedSKUsToInsert = new List<Affected_SKU__c>();
                    Decimal totalrefundprice = 0;
                    if (orderItemsToUpdate != null && !orderItemsToUpdate.isEmpty()) {
                        //update orderItemsToUpdate;
                        for(OrderItem ori : orderItemsToUpdate){
                            
                            if(ori.Is_Already_Utilized__c != true){
                                Affected_SKU__c affectedSKUrec = new Affected_SKU__c();
                                affectedSKUrec.Name = ori.SKU__c;
                                affectedSKUrec.Brand_Name__c = ori.Brand__c;
                                affectedSKUrec.MRP__c = ori.UnitPrice;
                                affectedSKUrec.Product_Name__c = ori.Product_Name__c;
                                affectedSKUrec.Case__c = caseRecord.Id;
                                affectedSKUsToInsert.add(affectedSKUrec);
                            }
                            //ori.Refund_Reasons__c = refundValue;
                            ori.Is_Already_Utilized__c = true;
                            updateAllOrderItems.add(ori);
                            if(ori.Refund_Price__c != null){
                                
                                totalrefundprice = totalrefundprice + ori.Refund_Price__c;
                                
                                System.debug('totalrefundprice======>'+totalrefundprice);
                            }
                            
                        }
                        System.debug('affectedSKUsToInsert==> '+ affectedSKUsToInsert);
                        if(!affectedSKUsToInsert.isEmpty()){
                            insert affectedSKUsToInsert;
                        }
                        if(totalrefundprice > 0){
                            orderRecord.Refund_Amount__c = totalrefundprice;
                            
                        }
                        update orderRecord;
                        update updateAllOrderItems;
                    }
                }
                
                
                //creating Task based on the userID(refundTeamMemberId)
                
                Task newTask = new Task();
                newTask.Subject = 'Case has been assigned to Move to Refund Team';
                newTask.Description = 'Please Move To Refund Team case with case ID: ' + caseRecord.Id;
                newTask.WhatId = caseRecord.Id; 
                //newTask.OwnerId = refundTeamMemberId; 
                insert newTask;
                System.debug('newTask====>'+newTask);
                
                // if(caseRecord!= null && caseRecord.AccountId != null){
                //     List<AccountShare> existingAccShareRec = [SELECT Id, AccountId, UserOrGroupId, AccountAccessLevel, OpportunityAccessLevel, CaseAccessLevel, 
                //     ContactAccessLevel, RowCause, LastModifiedDate, LastModifiedById, IsDeleted FROM AccountShare WHERE AccountId =: caseRecord.AccountId AND UserOrGroupId =: refundTeamMemberId];
                //     if(!existingAccShareRec.isEmpty()){
                //         delete existingAccShareRec;
                //     }else{
                //         AccountShare newAccShare = new AccountShare();
                //         newAccShare.AccountId = caseRecord.AccountId;
                //         newAccShare.UserOrGroupId = refundTeamMemberId;
                //         newAccShare.AccountAccessLevel = 'Edit';
                //         //newAccShare.ContactAccessLevel = 'Edit';
                //         newAccShare.OpportunityAccessLevel = 'Edit';
                //         newAccShare.CaseAccessLevel = 'Edit';
                //         insert newAccShare;
                //         System.debug('newAccShare======>'+newAccShare);
                //     }
                // }
                
                
                //create a case share record with Edit Access to the Refund team Member
                
                List<CaseShare> existingShares = [SELECT Id FROM CaseShare WHERE CaseId = :caseRecord.Id AND UserOrGroupId = :CSteamId];
                System.debug('existingShares======>'+existingShares);
                
                if(!existingShares.isEmpty()){
                    //delete existingShares;
                    System.debug('existingShares delete records======>'+existingShares);
                }else{
                    CaseShare newCaseShare = new CaseShare();
                    newCaseShare.CaseId =  caseId;    //caseRecord.Id;
                    System.debug('caseId=======>'+caseId);      
                    newCaseShare.UserOrGroupId = CSteamId;
                    System.debug('CSteamId=====>'+CSteamId);
                    newCaseShare.CaseAccessLevel = 'Edit';
                    //newCaseShare.RowCause = Schema.CaseShare.RowCause.Manual;
                    insert newCaseShare;
                    System.debug('newCaseShare======>'+newCaseShare);
                }
                
                
                
                
                //Approval processes to fire
                
                /* Approval.ProcessSubmitRequest req= new Approval.ProcessSubmitRequest();
req.setComments('Submitting record for Approval');
req.setObjectId(caseRecord.id);
req.setNextApproverIds(new Id[] {caseRecord.RefundTeamMember__c});
req.setSubmitterId(caseRecord.ownerId); 
req.setProcessDefinitionNameOrId('When_Case_Is_Moved_to_ReFund_Team_Member');
Approval.ProcessResult approvalresult = Approval.process(req); */
                
                //Custom Notification call from this  (sendingCustomNotification) Method!
                //sendingCustomNotification(refundTeamMemberId, caseId, 'A case has been assigned', 'A case has been assigned to you to process the refund.');
                
                
                
                result = 'success';
            }
            
        }catch(Exception e){
            system.debug('Exception Message--->'+e.getMessage());
            system.debug('Exception Line Number--->'+e.getLineNumber());
            return e.getMessage();
        }
        return result;
        
    }
    
    @AuraEnabled
    public static void sendingCustomNotification(String refundTeamMemberId,String caseId,String notificationTitle, String notificationBody){
        
        System.debug('refundTeamMemberId====>'+refundTeamMemberId);
        System.debug('caseId====>'+caseId);
        CustomNotificationType notificationType = [SELECT Id, DeveloperName FROM CustomNotificationType 
                                                   WHERE DeveloperName='Refund_Team_Member'];
        
        
        Messaging.CustomNotification notification = new Messaging.CustomNotification();
        notification.setTitle(notificationTitle);
        notification.setBody(notificationBody);
        notification.setNotificationTypeId(notificationType.Id);
        notification.setTargetId(caseId);                         
        Set<String> addressee = new Set<String>();
        addressee.add(refundTeamMemberId);                         
        try {
            notification.send(addressee);
        }
        catch (Exception e) {
            System.debug('Problem sending notification: ' + e.getMessage());
        }
        
    }
    
    public class RefundWrapper {
        
        @AuraEnabled
        public Case caseRecord { get; set; }
        @AuraEnabled
        public Order orderRecord { get; set; }
        @AuraEnabled
        public List<OrderItem> orderItems { get; set; }
        
        public RefundWrapper(Case caseRecord, Order orderRecord, List<OrderItem> orderItems) {
            this.caseRecord = caseRecord;
            this.orderRecord = orderRecord;
            this.orderItems = orderItems;
        }
    }
}