force-app/main/default/objects/Affected_SKU__c/Affected_SKU__c.object-meta.xml
<CustomObject>
    <label>Affected SKU</label>
    <nameField>
        <label>Affected SKU Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Affected SKUs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Affected_SKU__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Affected SKUs</relationshipLabel>
    <relationshipName>Affected_SKUs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/affectedSKUtriggerHelper.cls
public with sharing class affectedSKUtriggerHelper {
    public static void deleteOldAndCreateNew(List<Affected_SKU__c> skuList) {
        try{
            Set<Id> caseIds = new Set<id>();
            for(Affected_SKU__c skuRec : skuList){
                if(skuRec.Case__c != null){
                    caseIds.add(skuRec.Case__c);
                }
            }
            if(!caseIds.isEmpty()){
                delete [SELECT Id, Name FROM Affected_SKU__c WHERE Case__c IN :caseIds];
            }
        }catch(exception e){
            System.debug('Error Message==> ' + e.getMessage() + ' at Line Number==> ' + e.getLineNumber());
        }
    }
}