force-app/main/default/objects/Call_Logs_Custom__c/Call_Logs_Custom__c.object-meta.xml
<CustomObject>
    <label>Call Logs Custom</label>
    <nameField>
        <displayFormat>CLC-{0000}</displayFormat>
        <label>Call Logs Custom Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Logs Customs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Call_Logs_Custom__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Call Logs Customs</relationshipLabel>
    <relationshipName>Call_Logs_Customs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Call_Logs_Custom__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Call Logs Customs</relationshipLabel>
    <relationshipName>Call_Logs_Customs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Call_Logs_Custom__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Queued</fullName>
            </value>
            <value>
                <fullName>In-progress</fullName>
            </value>
            <value>
                <fullName>Ringing</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Busy</fullName>
            </value>
            <value>
                <fullName>No-answer</fullName>
            </value>
            <value>
                <fullName>Missed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CallLogTriggerHelperTest.cls
@istest(seeAllData = false)
public class CallLogTriggerHelperTest {
    @istest
    public static void collectEmailOrPhoneOfCallLogs(){
        
        List<Call_Logs_Custom__c> clgList= new List<Call_Logs_Custom__c>();
        List<Case> caselist =new List<Case>();
       Account acc = new Account();
        acc.Name = 'Testing';
        acc.Phone = '098765432123456';
        Insert acc;
        
        Contact con = new Contact();
        con.accountId = acc.Id;
        con.Email = 'new@contact.com';
        con.FirstName = 'Test';
        con.LastName = 'contact';
        Insert Con;
        
        
        Case cse = new Case();
        cse.Origin = 'Bulk Upload';
        cse.Status = 'New';
        cse.AccountId = acc.Id;
        cse.ContactId = con.Id;
        Insert cse;
 
        Call_Logs_Custom__c clg = new Call_Logs_Custom__c();
        clg.Phone__c = '9025244424';
        clg.Email__c = 'banoj253@gmail.com';
        Insert clg;
        Datetime myDate = Datetime.newInstance(2024, 04, 1, 12, 30, 2);
        Test.setCreatedDate(clg.Id, myDate);
        Call_Logs_Custom__c clgq = [Select Id,Name,IsDeleted,CreatedDate,Phone__c,Contact__c,OwnerId,Case__c ,Email__c,Status__c FROM  Call_Logs_Custom__c WHERE ID=: clg.Id LIMIT 1];
        System.debug('CreatedDate====>'+clgq.CreatedDate);
        clgq.Contact__c = con.Id;
        clgq.Case__c = cse.Id;
        clgq.Status__c = 'Missed';
        update clgq;
        clgList.add(clgq);
        CallLogTriggerHelper.collectEmailOrPhoneOfCallLogs(clgList);  
        clgList.clear();
        Call_Logs_Custom__c clgq1 = [Select Id,Name,IsDeleted,CreatedDate,Phone__c,Contact__c,OwnerId,Case__c ,Email__c,Status__c FROM  Call_Logs_Custom__c WHERE ID=: clg.Id LIMIT 1];
        clgq1.Contact__c = con.Id;
        clgq1.Case__c = cse.Id;
        clgq1.Status__c = 'In-progress';
        update clgq1;
        clgList.add(clgq1);
        
        /*Call_Logs_Custom__c clg1 = new Call_Logs_Custom__c();
        clg.Phone__c = '9025244424';
        clg.Email__c = 'banoj253@gmail.com';
        //clg.CreatedDate = System.Now();
        Insert clg1;
        Datetime myDate1 = Datetime.newInstance(2024, 04, 1, 12, 30, 2);
        Test.setCreatedDate(clg1.Id, myDate1);
        Call_Logs_Custom__c clgq1 = [Select Id,Name,IsDeleted,CreatedDate,Phone__c,Contact__c,Case__c ,Email__c,Status__c,OwnerId FROM  Call_Logs_Custom__c WHERE Id=:clg1.Id Limit 1];
        //System.debug('CreatedDate====>'+clgq1.CreatedDate);
            
        clgq1.Contact__c = con.Id;
        clgq1.Case__c = cse.Id;
        clgq1.Status__c = 'In-progress';
        //update clg1;
        clgList.add(clgq1);*/
        update clgList;                                           
       CallLogTriggerHelper.collectEmailOrPhoneOfCallLogs(clgList);  
       
    }
}