force-app/main/default/objects/Instagram_Api_Details__c/Instagram_Api_Details__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Instagram Api Details</label>
</CustomObject>

force-app/main/default/objects/Instagram_Api_Details__c/fields/HashTag__c.field-meta.xml
<CustomField>
    <fullName>HashTag__c</fullName>
    <label>HashTag(#)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ScheduleInstagramBatchForHashTags.cls
public class ScheduleInstagramBatchForHashTags implements schedulable {
    private static Instagram_Api_Details__c fap = Instagram_Api_Details__c.getInstance();	
    private static final String hashTag         = fap.HashTag__c;
    public void execute(SchedulableContext sc){
         InstagramHashTagCreationBatch batch = new InstagramHashTagCreationBatch();
         Database.executeBatch(batch);
    }
}