force-app/main/default/objects/Working_Hour__mdt/Working_Hour__mdt.object-meta.xml
<CustomObject>
    <label>Working Hour</label>
    <pluralLabel>Working Hours</pluralLabel>
</CustomObject>

force-app/main/default/objects/Working_Hour__mdt/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <label>End Time</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>5:00</fullName>
                <default>true</default>
                <label>5:00</label>
            </value>
            <value>
                <fullName>5:15</fullName>
            </value>
            <value>
                <fullName>5:30</fullName>
            </value>
            <value>
                <fullName>5:45</fullName>
            </value>
            <value>
                <fullName>6:00</fullName>
            </value>
            <value>
                <fullName>6:15</fullName>
            </value>
            <value>
                <fullName>6:30</fullName>
            </value>
            <value>
                <fullName>6:45</fullName>
            </value>
            <value>
                <fullName>7:00</fullName>
            </value>
            <value>
                <fullName>7:15</fullName>
            </value>
            <value>
                <fullName>7:30</fullName>
            </value>
            <value>
                <fullName>7:45</fullName>
            </value>
            <value>
                <fullName>8:00</fullName>
            </value>
            <value>
                <fullName>8:15</fullName>
            </value>
            <value>
                <fullName>8:30</fullName>
            </value>
            <value>
                <fullName>8:45</fullName>
            </value>
            <value>
                <fullName>9:00</fullName>
            </value>
            <value>
                <fullName>9:15</fullName>
            </value>
            <value>
                <fullName>9:30</fullName>
            </value>
            <value>
                <fullName>9:45</fullName>
            </value>
            <value>
                <fullName>10:00</fullName>
            </value>
            <value>
                <fullName>10:15</fullName>
            </value>
            <value>
                <fullName>10:30</fullName>
            </value>
            <value>
                <fullName>10:45</fullName>
            </value>
            <value>
                <fullName>11:00</fullName>
            </value>
            <value>
                <fullName>11:15</fullName>
            </value>
            <value>
                <fullName>11:30</fullName>
            </value>
            <value>
                <fullName>11:45</fullName>
            </value>
            <value>
                <fullName>12:00</fullName>
            </value>
            <value>
                <fullName>12:15</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Working_Hour__mdt/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <label>Start Time</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>5:00</fullName>
                <default>true</default>
                <label>5:00</label>
            </value>
            <value>
                <fullName>5:15</fullName>
            </value>
            <value>
                <fullName>5:30</fullName>
            </value>
            <value>
                <fullName>5:45</fullName>
            </value>
            <value>
                <fullName>6:00</fullName>
            </value>
            <value>
                <fullName>6:15</fullName>
            </value>
            <value>
                <fullName>6:30</fullName>
            </value>
            <value>
                <fullName>6:45</fullName>
            </value>
            <value>
                <fullName>7:00</fullName>
            </value>
            <value>
                <fullName>7:15</fullName>
            </value>
            <value>
                <fullName>7:30</fullName>
            </value>
            <value>
                <fullName>7:45</fullName>
            </value>
            <value>
                <fullName>8:00</fullName>
            </value>
            <value>
                <fullName>8:15</fullName>
            </value>
            <value>
                <fullName>8:30</fullName>
            </value>
            <value>
                <fullName>8:45</fullName>
            </value>
            <value>
                <fullName>9:00</fullName>
            </value>
            <value>
                <fullName>9:15</fullName>
            </value>
            <value>
                <fullName>9:30</fullName>
            </value>
            <value>
                <fullName>9:45</fullName>
            </value>
            <value>
                <fullName>10:00</fullName>
            </value>
            <value>
                <fullName>10:15</fullName>
            </value>
            <value>
                <fullName>10:30</fullName>
            </value>
            <value>
                <fullName>10:45</fullName>
            </value>
            <value>
                <fullName>11:00</fullName>
            </value>
            <value>
                <fullName>11:15</fullName>
            </value>
            <value>
                <fullName>11:30</fullName>
            </value>
            <value>
                <fullName>11:45</fullName>
            </value>
            <value>
                <fullName>12:00</fullName>
            </value>
            <value>
                <fullName>12:15</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/kultBotApex.cls
public class kultBotApex {
    public class timeOutput{
        @InvocableVariable
        public Boolean isInWorkingHour;
    }
    
    @InvocableMethod(label='Get Working Hour') 
    public static List<timeOutput> isInWorkHours(){
        try{
            List<Working_Hour__mdt> workHour = [SELECT Id, Label, Start_Time__c, End_Time__c FROM Working_Hour__mdt WHERE Label='Chat Support Team'];
            List<timeOutput> toList = new List<timeOutput>();
            timeOutput to = new timeOutput();
            if(workHour.Size()>0){
                Working_Hour__mdt whRec = workHour[0];
                List<String> startTimeSplit = whRec.Start_Time__c.split(':');
                List<String> endTimeSplit = whRec.End_Time__c.split(':');
                Time startTime = Time.newInstance(Integer.valueOf(startTimeSplit[0]), Integer.valueOf(startTimeSplit[1]), 0, 0);
                Time endTime = Time.newInstance(Integer.valueOf(endTimeSplit[0]), Integer.valueOf(endTimeSplit[1]), 0, 0);
                Time currentTime = System.Now().time();
                
                System.debug('startTime==> ' + startTime);
                System.debug('endTime==> ' + endTime);
                System.debug('currentTime==> ' + currentTime); 
                System.debug(currentTime>= startTime && currentTime <= endTime);
                if(currentTime>= startTime && currentTime <= endTime){
                    to.isInWorkingHour = true;
                    toList.add(to);
                 	return toList;   
                }else{
                    to.isInWorkingHour = false;
                    toList.add(to);
                 	return toList;
                }
            }
            return null;
        }catch(exception e){
            System.debug('Error Message:: ' + e.getMessage() + ' at line number:: ' + e.getLineNumber());
            return null;
        }
    }
}